-- ============================================================================
-- MOVED → sql/01_ludo_schema.sql
-- ============================================================================
-- All Ludo SQL now lives in the sql/ folder, numbered in the order it must be
-- run. See sql/README.md.
--
--   sql/01_ludo_schema.sql   base tables + original RPCs (fresh DB only)
--   sql/02_ludo_fixes.sql    REQUIRED — missing RPCs/columns, race guards, locks
--   sql/03_ludo_cron.sql     REQUIRED — janitor for stuck rooms / queue refunds
--   sql/99_verify.sql        optional read-only PASS/FAIL report
--
-- This stub is kept so old links don't break. It is safe to delete.
-- ============================================================================
