name = "ludzo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages with Next.js
# Build command: npx @cloudflare/next-on-pages
# Build output directory: .vercel/output/static

[vars]
NEXT_PUBLIC_TELEGRAM_BOT_USERNAME = "LudzoBot"
NEXT_PUBLIC_MONETAG_ZONE_ID = "11113056"
