"use client";
import { useCallback, useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { showToast } from "@/components/ui/Toast";

type Profile={id:string;display_name:string;avatar_url:string;coin_balance:number;usdt_balance:number;active:boolean};
export default function DisplayProfiles(){const [items,setItems]=useState<Profile[]>([]);const [form,setForm]=useState({display_name:"",avatar_url:"",coin_balance:"0",usdt_balance:"0"});const token=()=>localStorage.getItem("ludzo_admin_token")??"";
 const load=useCallback(async()=>{const r=await fetch("/api/admin/display-profiles",{headers:{Authorization:`Bearer ${token()}`}});if(r.status===401){location.href="/admin";return}const d=await r.json();if(d.success)setItems(d.data)},[]);useEffect(()=>{load()},[load]);
 async function add(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/display-profiles",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify(form)});const d=await r.json();if(d.success){setForm({display_name:"",avatar_url:"",coin_balance:"0",usdt_balance:"0"});showToast("Display profile added","success");load()}else showToast(d.error??"Could not add profile","error")}
 async function toggle(p:Profile){await fetch("/api/admin/display-profiles",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify({...p,active:!p.active})});load()}
 const input=(key:keyof typeof form,ph:string)=><input required placeholder={ph} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full rounded-xl border border-[#333] bg-[#1a1a1a] px-3 py-2 text-sm text-white"/>;
 return <AdminShell title="Display Profiles"><div className="p-4 md:p-6 space-y-5 max-w-3xl"><div className="rounded-2xl border border-[#333] bg-[#111] p-5"><h2 className="font-bold text-white">Add leaderboard profile</h2><p className="text-xs text-gray-500 mt-1 mb-4">Interface-only profile. It is never a real Telegram account or a playable bot.</p><form onSubmit={add} className="grid sm:grid-cols-2 gap-3">{input("display_name","Display name")}{input("avatar_url","Public image URL")}{input("coin_balance","Coins")}{input("usdt_balance","USDT") }<button className="sm:col-span-2 rounded-xl bg-[#23856C] py-2.5 font-bold text-white">Add profile</button></form></div><div className="space-y-2">{items.map(p=><div key={p.id} className="flex items-center gap-3 rounded-xl border border-[#222] bg-[#111] p-3"><img src={p.avatar_url} className="h-10 w-10 rounded-full object-cover"/><div className="flex-1"><div className="font-semibold text-white">{p.display_name}</div><div className="text-xs text-gray-500">{p.coin_balance} coins · {p.usdt_balance} USDT</div></div><button onClick={()=>toggle(p)} className="rounded-lg bg-white/10 px-3 py-2 text-xs text-gray-300">{p.active?"Disable":"Enable"}</button></div>)}</div></div></AdminShell>}
