// Keep this list as the single source of truth for onboarding, settings and
// server-side preference validation. The names are intentionally native so a
// person can recognise a language before changing the app language.
export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English",    nativeName: "English",    country: "United States", countryCode: "US" },
  { code: "ru", name: "Russian",    nativeName: "Русский",    country: "Russia",        countryCode: "RU" },
  { code: "uk", name: "Ukrainian",  nativeName: "Українська", country: "Ukraine",      countryCode: "UA" },
  { code: "es", name: "Spanish",    nativeName: "Español",    country: "Spain",        countryCode: "ES" },
  { code: "pt", name: "Portuguese", nativeName: "Português",  country: "Portugal",     countryCode: "PT" },
  { code: "fr", name: "French",     nativeName: "Français",   country: "France",       countryCode: "FR" },
  { code: "de", name: "German",     nativeName: "Deutsch",    country: "Germany",      countryCode: "DE" },
  { code: "it", name: "Italian",    nativeName: "Italiano",   country: "Italy",        countryCode: "IT" },
  { code: "tr", name: "Turkish",    nativeName: "Türkçe",     country: "Türkiye",      countryCode: "TR" },
  { code: "hi", name: "Hindi",      nativeName: "हिन्दी",      country: "India",        countryCode: "IN" },
] as const;

export type LanguageCode = (typeof SUPPORTED_LANGUAGES)[number]["code"];

export function isSupportedLanguage(value: unknown): value is LanguageCode {
  return typeof value === "string" && SUPPORTED_LANGUAGES.some((language) => language.code === value);
}

export function normalizeLanguage(value: unknown): LanguageCode {
  if (typeof value !== "string") return "en";
  const code = value.toLowerCase().split("-")[0].trim();
  return isSupportedLanguage(code) ? code : "en";
}

const EN: Record<string, string> = {
  // Nav
  nav_home: "Home", nav_tasks: "Tasks", nav_games: "Games", nav_refer: "Refer", nav_profile: "Profile", nav_play: "Play", nav_matches: "Matches", nav_settings: "Settings", nav_arena: "Ludo Arena",
  // Common
  loading: "Loading...", error: "Something went wrong", retry: "Retry", cancel: "Cancel", save: "Save", confirm: "Confirm", close: "Close", submit: "Submit", back: "Back", next: "Next", done: "Done", copy: "Copy", share: "Share", copied: "Copied!", search: "Search", all: "All", status: "Status", date: "Date", amount: "Amount", view_all: "View All", details: "Details", success: "Success", failed: "Failed", coins: "Coins", usdt: "USDT", won_coins: "Won Coins", or: "or",
  // Splash / Onboarding
  splash_tagline: "Your next move starts here.", splash_bottom: "PLAY. EARN. REPEAT.", onboarding_kicker: "LET’S GET YOU STARTED", onboarding_title: "A space that speaks your language.", onboarding_subtitle: "Choose your preferred language. You can change it later in settings.", onboarding_continue: "Continue", onboarding_secure: "Secure sign-in with Telegram",
  // Auth
  sign_in_tg: "Sign In with Telegram", dev_mode: "Continue (Dev Mode)", authenticating: "Authenticating...", verifying_tg: "Verifying your Telegram identity", welcome_ludzo: "Welcome to LUDZO!", redirecting: "Redirecting...", connect_title: "Let’s get you connected", connect_no_tg: "Could not detect Telegram. Please open this app inside Telegram.",
  // Home
  welcome_user: "Welcome back, {name}", workspace_sub: "Here’s what’s happening in your workspace.", eyebrow: "THE LUDZO WORKSPACE", hero_heading: "Make your next move count.", hero_desc: "Play a round. Build your streak. Keep all your rewards in one place.", enter_arena: "Enter the arena", your_wallet: "Your wallet", balances_glance: "Balances at a glance", recent_activity: "Recent Activity", no_activity: "No activity yet", no_activity_desc: "Start watching ads or playing games to earn Coins!", top_earners: "Top Earners", announcements: "Announcements",
  // Wallet / Deposit / Withdraw
  playable_coins: "Playable coins", available_balance: "Available balance", won_coins_title: "Won coins", ready_to_withdraw: "Ready to withdraw", convertible_value: "${amount} convertible", ludo_prizes_note: "Ludo prizes · {rate} Won Coins = $1", coins_rate_note: "{rate} Coins = $1", deposit: "Deposit", withdraw: "Withdraw",
  deposit_title: "Buy Coins", select_network: "Select Network", complete_payment: "Complete Payment", current_balance: "Current Balance", select_amount: "Select Amount", custom_amount: "Custom amount ({min}–{max})", custom_hint: "Enter the exact number of Coins you want to receive.", you_pay: "You pay", continue_amount: "Continue — {count} Coins (${amount})", choose_network: "Choose payment network", important_notice: "Important Notice", deposit_notice_text: "The exact payment amount shown by Ludzo must be received after network fees.", agree_terms: "I understand and agree that the exact payment amount must be received after all exchange and network fees.", generate_address: "Generate Payment Address", creating_payment: "Creating Payment…", deposit_history: "Deposit History", no_deposits: "No deposits yet", no_deposits_desc: "Make your first deposit above.",
  withdraw_title: "Withdraw USDT", withdrawal_request: "Withdrawal Request", min_withdraw_note: "Minimum withdrawal is ${amount}", fee_note: "{fee}% withdrawal fee applies", review_note: "Withdrawals are manually reviewed within 48 hours", wallet_address_label: "Wallet Address (TRC20 / BEP20)", submit_withdrawal: "Submit Withdrawal Request", submitting: "Submitting…", withdrawal_history: "Withdrawal History", no_withdrawals: "No withdrawals yet", no_withdrawals_desc: "Submit your first withdrawal above.", insufficient_balance: "Insufficient balance",
  // Ads & Streak
  rewarded_ads: "Rewarded ads", limit_reached: "Daily limit reached · come back tomorrow", ads_left_today: "{remaining} left today", watch_ad: "Watch ad", earned_coins_toast: "+{amount} Coins earned!", coins_per_ad: "+{amount} coins / ad",
  daily_streak: "Daily streak", day_claimed: "Day {n} claimed", day_of_7: "Day {n} of 7", earned_today: "earned today", coins_today: "coins today", come_back_tomorrow: "Come back tomorrow for Day {n}", bonus_ads_progress: "Bonus ads {count}/{needed}", bonus_ad_btn: "Bonus ad", claim_btn: "Claim", streak_claimed_toast: "Streak Day {n} claimed! +{amount} Coins",
  // Tasks
  tasks_title: "Tasks", available: "Available", completed: "Completed", no_available_tasks: "All tasks completed!", no_available_tasks_desc: "Check back later for new tasks.", open_channel: "Open Channel", start_task: "Start Task", verify_claim: "Verify & Claim", bot_check_note: "Coins are awarded only when you join — the bot verifies membership.", already_done: "Task already completed",
  // Refer
  refer_title: "Refer & Earn", referrals_stat: "Referrals", total_stat: "Total", pending_stat: "Pending", your_referral_link: "Your Referral Link", copy_link: "Copy Link", how_it_works: "How It Works", refer_step_1: "Share your unique referral link", refer_step_2: "New user joins and gets 10 Coins bonus", refer_step_3: "They make their first deposit", refer_step_4: "You earn 10% commission in USDT", referral_history: "Referral History", no_referrals_yet: "No referrals yet", no_referrals_desc: "Share your link to start earning commission.",
  // Leaderboard
  leaderboard_title: "Leaderboard", leaderboard_sub: "Top players earning rewards on LUDZO", weekly: "Weekly", monthly: "Monthly", all_time: "All-Time", rank: "Rank", player: "Player", earned: "Earned", your_rank: "Your Rank", no_leaderboard: "No leaderboard data available yet.",
  // Profile
  profile_title: "Profile", wallet_summary: "Wallet Summary", coins_wallet: "Coins Wallet", cash_wallet: "Cash Wallet", won_coins_ludo: "Won Coins (Ludo prizes)", menu_ludo: "Ludo Arena", menu_history: "Transaction History", menu_leaderboard: "Leaderboard", menu_refer: "Refer & Earn", menu_faq: "FAQ", menu_support: "Support", menu_disputes: "Support & Disputes", menu_settings: "Settings", menu_legal: "Legal Center", sign_out: "Sign Out",
  // Settings
  appearance: "Appearance", theme_dark: "Dark", theme_light: "Light", theme_system: "System", language_setting: "Language", language_sub: "Choose how LUDZO speaks to you", languages_available: "{count} available", save_settings: "Save Settings", settings_saved: "Settings saved!", failed_save: "Failed to save settings",
  // History
  history_title: "Transaction History", filter_deposits: "Deposits", filter_withdrawals: "Withdrawals", filter_ads: "Ads", filter_tasks: "Tasks", filter_referrals: "Referrals", no_transactions: "No transactions", no_transactions_desc: "No transactions found for this filter.", load_more: "Load More",
  // Games & Ludo
  gamer_lobby: "Gamer Lobby", exit_hub: "Exit Hub", ludo_clash: "LUDO CLASH", ludo_desc: "Battle live players, roll the dice and claim the Coin pool instantly.", play_ludo_now: "Play Ludo Now", recent_battles: "Recent Battles", no_battles: "No battles yet", no_battles_desc: "Your finished matches and Coin results will show up here.", choose_stake: "Choose your stake", winner_payout: "Winner receives 98% of the pool", how_to_play: "How to play", play_for_stake: "Play for {amount} Coins", confirm_entry: "Enter for {count} Coins", confirm_sub: "Your stake is held in escrow until the match is settled.", join_match: "Join match", searching_opponent: "Searching for an opponent", cancel_matchmaking: "Cancel matchmaking", your_turn: "Your turn", opponents_turn: "Opponent's turn", roll_btn: "Roll!", rolling: "Rolling", rolled: "Rolled", forfeit_match: "Forfeit match?", forfeit_desc: "You will lose your {amount} coin stake. Your opponent takes the pool.", keep_playing: "Keep Playing", forfeit_btn: "Forfeit", victory: "VICTORY!", defeated: "DEFEATED", victory_desc: "Outstanding play! Rewards credited to your Won Coins balance.", defeated_desc: "A tough match! Come back stronger next time.", return_lobby: "Return to Lobby", tap_to_move: "Tap a piece to move", battle_history: "Battle History", game_profile: "Game Profile", clear_cache: "Clear Local Cache", cache_cleared: "Local cache cleared — balances reloaded from the server.",
  // Support & FAQ
  support_title: "Support", chat_support: "Chat with Support", chat_support_desc: "Get instant help via Telegram. Response time: usually within a few hours.", open_telegram: "Open Telegram", submit_ticket: "Submit a Ticket", category: "Category", subject: "Subject", message: "Message", send_ticket: "Send Ticket", ticket_submitted: "Ticket Submitted!", my_tickets: "My Tickets", no_tickets: "No tickets yet. Submit one above and it will show up here with our reply.", add_reply: "+ Add a reply", browse_category: "Browse by Category", faq_title: "FAQ",
  // Legal
  legal_center: "Legal Center", legal_desc: "Everything you need to know about how LUDZO operates, your rights, and our policies.", terms_cond: "Terms & Conditions", privacy_policy: "Privacy Policy", resp_gaming: "Responsible Gaming Policy", refund_policy: "Refund Policy", aml_policy: "AML & Anti-Fraud Policy", fair_play: "Fair Play Policy", support_disputes: "Support & Disputes",
  // Maintenance
  under_maintenance: "Under Maintenance", maintenance_desc: "LUDZO is currently undergoing scheduled maintenance. Please check back shortly.",
};

const RU: Record<string, string> = { ...EN,
  nav_home: "Главная", nav_tasks: "Задания", nav_games: "Игры", nav_refer: "Рефералы", nav_profile: "Профиль", nav_play: "Играть", nav_matches: "Матчи", nav_settings: "Настройки", nav_arena: "Арена Ludo",
  loading: "Загрузка...", error: "Что-то пошло не так", retry: "Повторить", cancel: "Отмена", save: "Сохранить", confirm: "Подтвердить", close: "Закрыть", submit: "Отправить", back: "Назад", next: "Далее", done: "Готово", copy: "Копировать", share: "Поделиться", copied: "Скопировано!", search: "Поиск", all: "Все", status: "Статус", date: "Дата", amount: "Сумма", view_all: "Смотреть все", details: "Детали", success: "Успешно", failed: "Ошибка", coins: "Монеты", usdt: "USDT", won_coins: "Выигранные монеты", or: "или",
  splash_tagline: "Ваш следующий ход начинается здесь.", splash_bottom: "ИГРАЙ. ЗАРАБАТЫВАЙ. ПОВТОРЯЙ.", onboarding_kicker: "ДАВАЙТЕ НАЧНЕМ", onboarding_title: "Пространство, говорящее на вашем языке.", onboarding_subtitle: "Выберите предпочитаемый язык. Вы сможете изменить его позже в настройках.", onboarding_continue: "Продолжить", onboarding_secure: "Безопасный вход через Telegram",
  sign_in_tg: "Войти через Telegram", dev_mode: "Продолжить (Dev режим)", authenticating: "Аутентификация...", verifying_tg: "Проверка профиля Telegram", welcome_ludzo: "Добро пожаловать в LUDZO!", redirecting: "Перенаправление...", connect_title: "Давайте подключимся", connect_no_tg: "Telegram не обнаружен. Откройте приложение внутри Telegram.",
  welcome_user: "С возвращением, {name}", workspace_sub: "Вот что происходит в вашем рабочем пространстве.", eyebrow: "РАБОЧЕЕ ПРОСТРАНСТВО LUDZO", hero_heading: "Сделайте ваш следующий ход решающим.", hero_desc: "Сыграйте раунд. Поддерживайте серию. Храните награды в одном месте.", enter_arena: "Войти на арену", your_wallet: "Ваш кошелек", balances_glance: "Баланс с первого взгляда", recent_activity: "Недавняя активность", no_activity: "Активности пока нет", no_activity_desc: "Смотрите рекламу или играйте, чтобы зарабатывать монеты!", top_earners: "Лидеры по заработку", announcements: "Объявления",
  playable_coins: "Монеты для игры", available_balance: "Доступный баланс", won_coins_title: "Выигранные монеты", ready_to_withdraw: "Готово к выводу", convertible_value: "${amount} доступно", ludo_prizes_note: "Призы Ludo · {rate} Выигранных монет = $1", coins_rate_note: "{rate} Монет = $1", deposit: "Пополнить", withdraw: "Вывести",
  deposit_title: "Купить монеты", select_network: "Выберите сеть", complete_payment: "Завершить оплату", current_balance: "Текущий баланс", select_amount: "Выберите сумму", custom_amount: "Своя сумма ({min}–{max})", custom_hint: "Введите точное количество монет, которое хотите получить.", you_pay: "Вы платите", continue_amount: "Продолжить — {count} Монет (${amount})", choose_network: "Выберите платежную сеть", important_notice: "Важное примечание", deposit_notice_text: "Точная сумма оплаты, указанная Ludzo, должна поступить с учетом комиссии сети.", agree_terms: "Я понимаю и соглашаюсь с тем, что точная сумма оплаты должна поступить за вычетом всех комиссий.", generate_address: "Сгенерировать адрес оплаты", creating_payment: "Создание платежа…", deposit_history: "История депозитов", no_deposits: "Депозитов пока нет", no_deposits_desc: "Сделайте ваш первый депозит выше.",
  withdraw_title: "Вывод USDT", withdrawal_request: "Запрос на вывод", min_withdraw_note: "Минимальная сумма вывода ${amount}", fee_note: "Применяется комиссия за вывод {fee}%", review_note: "Выводы проверяются вручную в течение 48 часов", wallet_address_label: "Адрес кошелька (TRC20 / BEP20)", submit_withdrawal: "Отправить запрос на вывод", submitting: "Отправка…", withdrawal_history: "История выводов", no_withdrawals: "Выводов пока нет", no_withdrawals_desc: "Оформите ваш первый вывод выше.", insufficient_balance: "Недостаточно средств",
  rewarded_ads: "Реклама с наградой", limit_reached: "Дневной лимит достигнут · приходите завтра", ads_left_today: "Осталось {remaining} сегодня", watch_ad: "Смотреть рекламу", earned_coins_toast: "+{amount} монет получено!", coins_per_ad: "+{amount} монет / просмотр",
  daily_streak: "Ежедневная серия", day_claimed: "День {n} получен", day_of_7: "День {n} из 7", earned_today: "заработано сегодня", coins_today: "монет сегодня", come_back_tomorrow: "Приходите завтра за Днем {n}", bonus_ads_progress: "Бонусная реклама {count}/{needed}", bonus_ad_btn: "Бонусное видео", claim_btn: "Забрать", streak_claimed_toast: "Награда за День {n} получена! +{amount} монет",
  tasks_title: "Задания", available: "Доступные", completed: "Завершенные", no_available_tasks: "Все задания выполнены!", no_available_tasks_desc: "Загляните позже, чтобы увидеть новые задания.", open_channel: "Открыть канал", start_task: "Начать задание", verify_claim: "Проверить и забрать", bot_check_note: "Монеты начисляются после вступления — бот проверяет подписку.", already_done: "Задание уже выполнено",
  refer_title: "Рефералы и заработок", referrals_stat: "Рефералы", total_stat: "Всего", pending_stat: "В ожидании", your_referral_link: "Ваша реферальная ссылка", copy_link: "Скопировать ссылку", how_it_works: "Как это работает", refer_step_1: "Поделитесь вашей уникальной ссылкой", refer_step_2: "Новый пользователь заходит и получает бонус 10 монет", refer_step_3: "Он делает свой первый депозит", refer_step_4: "Вы получаете 10% комиссии в USDT", referral_history: "История рефералов", no_referrals_yet: "Рефералов пока нет", no_referrals_desc: "Поделитесь ссылкой, чтобы начать получать комиссию.",
  leaderboard_title: "Таблица лидеров", leaderboard_sub: "Лучшие игроки, зарабатывающие награды в LUDZO", weekly: "За неделю", monthly: "За месяц", all_time: "За всё время", rank: "Ранг", player: "Игрок", earned: "Заработано", your_rank: "Ваш ранг", no_leaderboard: "Данные таблицы лидеров пока отсутствуют.",
  profile_title: "Профиль", wallet_summary: "Обзор кошелька", coins_wallet: "Кошелек монет", cash_wallet: "Денежный кошелек", won_coins_ludo: "Выигранные монеты (призы Ludo)", menu_ludo: "Арена Ludo", menu_history: "История транзакций", menu_leaderboard: "Таблица лидеров", menu_refer: "Реферальная программа", menu_faq: "Частые вопросы", menu_support: "Поддержка", menu_disputes: "Поддержка и споры", menu_settings: "Настройки", menu_legal: "Правовой центр", sign_out: "Выйти",
  appearance: "Внешний вид", theme_dark: "Темная", theme_light: "Светлая", theme_system: "Системная", language_setting: "Язык", language_sub: "Выберите, на каком языке общаться с LUDZO", languages_available: "{count} доступно", save_settings: "Сохранить настройки", settings_saved: "Настройки сохранены!", failed_save: "Не удалось сохранить настройки",
  history_title: "История транзакций", filter_deposits: "Депозиты", filter_withdrawals: "Выводы", filter_ads: "Реклама", filter_tasks: "Задания", filter_referrals: "Рефералы", no_transactions: "Нет транзакций", no_transactions_desc: "Транзакций для этого фильтра не найдено.", load_more: "Загрузить еще",
  gamer_lobby: "Игровое лобби", exit_hub: "Выйти из хаба", ludo_clash: "LUDO CLASH", ludo_desc: "Сражайтесь с игроками в реальном времени, бросайте кости и забирайте призовой фонд.", play_ludo_now: "Играть в Ludo сейчас", recent_battles: "Недавние битвы", no_battles: "Битв пока нет", no_battles_desc: "Здесь будут отображаться ваши завершенные матчи и результаты.", choose_stake: "Выберите ставку", winner_payout: "Победитель получает 98% призового фонда", how_to_play: "Как играть", play_for_stake: "Играть на {amount} монет", confirm_entry: "Войти за {count} монет", confirm_sub: "Ваша ставка удерживается на эскроу до окончания матча.", join_match: "Присоединиться к матчу", searching_opponent: "Поиск соперника", cancel_matchmaking: "Отменить подбор", your_turn: "Ваш ход", opponents_turn: "Ход соперника", roll_btn: "Бросить!", rolling: "Бросок", rolled: "Выпало", forfeit_match: "Сдаться?", forfeit_desc: "Вы потеряете ставку в {amount} монет. Соперник забрал банк.", keep_playing: "Продолжить игру", forfeit_btn: "Сдаться", victory: "ПОБЕДА!", defeated: "ПОРАЖЕНИЕ", victory_desc: "Отличная игра! Награда зачислена на баланс Выигранных монет.", defeated_desc: "Тяжелый матч! Вернитесь сильнее в следующий раз.", return_lobby: "Вернуться в лобби", tap_to_move: "Нажмите на фишку для хода", battle_history: "История битв", game_profile: "Игровой профиль", clear_cache: "Очистить локальный кэш", cache_cleared: "Локальный кэш очищен — балансы перезагружены с сервера.",
  support_title: "Поддержка", chat_support: "Чат с поддержкой", chat_support_desc: "Получите быструю помощь через Telegram. Время ответа: обычно пару часов.", open_telegram: "Открыть Telegram", submit_ticket: "Создать тикет", category: "Категория", subject: "Тема", message: "Сообщение", send_ticket: "Отправить тикет", ticket_submitted: "Тикет отправлен!", my_tickets: "Мои тикеты", no_tickets: "Тикетов пока нет. Создайте тикет выше, и он появится здесь.", add_reply: "+ Добавить ответ", browse_category: "Просмотр по категориям", faq_title: "Часто задаваемые вопросы",
  legal_center: "Правовой центр", legal_desc: "Все, что вам нужно знать о работе LUDZO, ваших правах и наших правилах.", terms_cond: "Условия и положения", privacy_policy: "Политика конфиденциальности", resp_gaming: "Ответственная игра", refund_policy: "Политика возврата", aml_policy: "Политика AML и борьбы с мошенничеством", fair_play: "Правила честной игры", support_disputes: "Поддержка и споры",
  under_maintenance: "На техническом обслуживании", maintenance_desc: "LUDZO находится на плановом обслуживании. Пожалуйста, зайдите позже.",
};

const UK: Record<string, string> = { ...EN,
  nav_home: "Головна", nav_tasks: "Завдання", nav_games: "Ігри", nav_refer: "Реферали", nav_profile: "Профіль", nav_play: "Грати", nav_matches: "Матчі", nav_settings: "Налаштування", nav_arena: "Арена Ludo",
  loading: "Завантаження...", error: "Щось пішло не так", retry: "Повторити", cancel: "Скасувати", save: "Зберегти", confirm: "Підтвердити", close: "Закрити", submit: "Надіслати", back: "Назад", next: "Далі", done: "Готово", copy: "Копіювати", share: "Поділитися", copied: "Скопійовано!", search: "Пошук", all: "Усі", status: "Статус", date: "Дата", amount: "Сума", view_all: "Дивитися все", details: "Деталі", success: "Успішно", failed: "Помилка", coins: "Монети", usdt: "USDT", won_coins: "Виграні монети", or: "або",
  splash_tagline: "Ваш наступний хід починається тут.", splash_bottom: "ГРАЙ. ЗАРОБЛЯЙ. ПОВТОРЮЙ.", onboarding_kicker: "ДАВАЙТЕ РОЗПОЧНЕМО", onboarding_title: "Простір, що розмовляє вашою мовою.", onboarding_subtitle: "Оберіть бажану мову. Ви зможете змінити її пізніше в налаштуваннях.", onboarding_continue: "Продовжити", onboarding_secure: "Безпечний вхід через Telegram",
  sign_in_tg: "Увійти через Telegram", dev_mode: "Продовжити (Dev режим)", authenticating: "Аутентифікація...", verifying_tg: "Перевірка профілю Telegram", welcome_ludzo: "Ласкаво просимо до LUDZO!", redirecting: "Перенаправлення...", connect_title: "Давайте підключимося", connect_no_tg: "Telegram не виявлено. Відкрийте застосунок всередині Telegram.",
  welcome_user: "З поверненням, {name}", workspace_sub: "Ось що відбувається у вашому робочому просторі.", eyebrow: "РОБОЧИЙ ПРОСТІР LUDZO", hero_heading: "Зробіть ваш наступний хід вирішальним.", hero_desc: "Зіграйте раунд. Підтримуйте серію. Зберігайте нагороди в одному місці.", enter_arena: "Увійти на арену", your_wallet: "Ваш гаманець", balances_glance: "Баланс з першого погляду", recent_activity: "Остання активність", no_activity: "Активності поки немає", no_activity_desc: "Дивіться рекламу або грайте, щоб заробляти монети!", top_earners: "Лідери за заробітком", announcements: "Оголошення",
  playable_coins: "Монети для гри", available_balance: "Доступний баланс", won_coins_title: "Виграні монети", ready_to_withdraw: "Готово до виведення", convertible_value: "${amount} доступно", ludo_prizes_note: "Призи Ludo · {rate} Виграних монет = $1", coins_rate_note: "{rate} Монет = $1", deposit: "Поповнити", withdraw: "Вивести",
  deposit_title: "Купити монети", select_network: "Оберіть мережу", complete_payment: "Завершити оплату", current_balance: "Поточний баланс", select_amount: "Оберіть суму", custom_amount: "Своя сума ({min}–{max})", custom_hint: "Введіть точну кількість монет, яку бажаєте отримати.", you_pay: "Ви платите", continue_amount: "Продовжити — {count} Монет (${amount})", choose_network: "Оберіть платіжну мережу", important_notice: "Важлива примітка", deposit_notice_text: "Точна сума оплати, вказана Ludzo, має надійти з урахуванням комісії мережі.", agree_terms: "Я розумію та погоджуюся, що точна сума оплати має надійти за вирахуванням усіх комісій.", generate_address: "Згенерувати адресу оплати", creating_payment: "Створення платежу…", deposit_history: "Історія депозитів", no_deposits: "Депозитів поки немає", no_deposits_desc: "Зробіть ваш перший депозит вище.",
  withdraw_title: "Виведення USDT", withdrawal_request: "Запит на виведення", min_withdraw_note: "Мінімальна сума виведення ${amount}", fee_note: "Застосовується комісія за виведення {fee}%", review_note: "Виведення перевіряється вручну протягом 48 годин", wallet_address_label: "Адреса гаманця (TRC20 / BEP20)", submit_withdrawal: "Надіслати запит на виведення", submitting: "Надсилання…", withdrawal_history: "Історія виведення", no_withdrawals: "Виведень поки немає", no_withdrawals_desc: "Оформіть ваше перше виведення вище.", insufficient_balance: "Недостатньо коштів",
  rewarded_ads: "Реклама з винагородою", limit_reached: "Денний ліміт досягнуто · приходьте завтра", ads_left_today: "Залишилося {remaining} сьогодні", watch_ad: "Дивитися рекламу", earned_coins_toast: "+{amount} монет отримано!", coins_per_ad: "+{amount} монет / перегляд",
  daily_streak: "Щоденна серія", day_claimed: "День {n} отримано", day_of_7: "День {n} з 7", earned_today: "зароблено сьогодні", coins_today: "монет сьогодні", come_back_tomorrow: "Приходьте завтра за Днем {n}", bonus_ads_progress: "Бонусна реклама {count}/{needed}", bonus_ad_btn: "Бонусне відео", claim_btn: "Забрати", streak_claimed_toast: "Нагороду за День {n} отримано! +{amount} монет",
  tasks_title: "Завдання", available: "Доступні", completed: "Завершені", no_available_tasks: "Усі завдання виконано!", no_available_tasks_desc: "Завітайте пізніше, щоб побачити нові завдання.", open_channel: "Відкрити канал", start_task: "Розпочати завдання", verify_claim: "Перевірити та забрати", bot_check_note: "Монети нараховуються після вступу — бот перевіряє підписку.", already_done: "Завдання вже виконано",
  refer_title: "Реферали та заробіток", referrals_stat: "Реферали", total_stat: "Всього", pending_stat: "Очікується", your_referral_link: "Ваше реферальне посилання", copy_link: "Скопіювати посилання", how_it_works: "Як це працює", refer_step_1: "Поділіться вашим унікальним посиланням", refer_step_2: "Новий користувач заходить та отримує бонус 10 монет", refer_step_3: "Він робить свій перший депозит", refer_step_4: "Ви отримуєте 10% комісії в USDT", referral_history: "Історія рефералів", no_referrals_yet: "Рефералів поки немає", no_referrals_desc: "Поділіться посиланням, щоб почати отримувати комісію.",
  leaderboard_title: "Таблиця лідерів", leaderboard_sub: "Кращі гравці, які заробляють нагороди в LUDZO", weekly: "За тиждень", monthly: "За місяць", all_time: "За весь час", rank: "Ранг", player: "Гравець", earned: "Зароблено", your_rank: "Ваш ранг", no_leaderboard: "Дані таблиці лідерів поки відсутні.",
  profile_title: "Профіль", wallet_summary: "Огляд гаманця", coins_wallet: "Гаманець монет", cash_wallet: "Грошовий гаманець", won_coins_ludo: "Виграні монети (призи Ludo)", menu_ludo: "Арена Ludo", menu_history: "Історія транзакцій", menu_leaderboard: "Таблиця лідерів", menu_refer: "Реферальна програма", menu_faq: "Часті запитання", menu_support: "Підтримка", menu_disputes: "Підтримка та спори", menu_settings: "Налаштування", menu_legal: "Правовий центр", sign_out: "Вийти",
  appearance: "Зовнішній вигляд", theme_dark: "Темна", theme_light: "Світла", theme_system: "Системна", language_setting: "Мова", language_sub: "Оберіть, якою мовою спілкуватися з LUDZO", languages_available: "{count} доступно", save_settings: "Зберегти налаштування", settings_saved: "Налаштування збережено!", failed_save: "Не вдалося зберегти налаштування",
  history_title: "Історія транзакцій", filter_deposits: "Депозити", filter_withdrawals: "Виведення", filter_ads: "Реклама", filter_tasks: "Завдання", filter_referrals: "Реферали", no_transactions: "Немає транзакцій", no_transactions_desc: "Транзакцій для цього фільтра не знайдено.", load_more: "Завантажити ще",
  gamer_lobby: "Ігрове лобі", exit_hub: "Вийти з хабу", ludo_clash: "LUDO CLASH", ludo_desc: "Змагайтеся з гравцями в реальному часі, кидайте кубики та забирайте призовий фонд.", play_ludo_now: "Грати в Ludo зараз", recent_battles: "Останні битви", no_battles: "Битв поки немає", no_battles_desc: "Тут відображатимуться ваші завершені матчі та результати.", choose_stake: "Оберіть ставку", winner_payout: "Переможець отримує 98% призового фонду", how_to_play: "Як грати", play_for_stake: "Грати на {amount} монет", confirm_entry: "Увійти за {count} монет", confirm_sub: "Ваша ставка утримується на ескроу до закінчення матчу.", join_match: "Приєднатися до матчу", searching_opponent: "Пошук суперника", cancel_matchmaking: "Скасувати підбір", your_turn: "Ваш хід", opponents_turn: "Хід суперника", roll_btn: "Кинути!", rolling: "Кидок", rolled: "Випало", forfeit_match: "Здатися?", forfeit_desc: "Ви втратите ставку у {amount} монет. Суперник забрав банк.", keep_playing: "Продовжити гру", forfeit_btn: "Здатися", victory: "ПЕРЕМОГА!", defeated: "ПОРАЗКА", victory_desc: "Чудова гра! Нагороду зараховано на баланс Виграних монет.", defeated_desc: "Важкий матч! Поверніться сильнішими наступного разу.", return_lobby: "Повернутися в лобі", tap_to_move: "Натисніть на фішку для ходу", battle_history: "Історія битв", game_profile: "Ігровий профіль", clear_cache: "Очистити локальний кеш", cache_cleared: "Локальний кеш очищено — баланси перезавантажено з сервера.",
  support_title: "Підтримка", chat_support: "Чат з підтримкою", chat_support_desc: "Отримайте швидку допомогу через Telegram. Час відповіді: зазвичай кілька годин.", open_telegram: "Відкрити Telegram", submit_ticket: "Створити тікет", category: "Категорія", subject: "Тема", message: "Повідомлення", send_ticket: "Надіслати тікет", ticket_submitted: "Тікет надіслано!", my_tickets: "Мої тікети", no_tickets: "Тікетів поки немає. Створіть тікет вище, і він з'явиться тут.", add_reply: "+ Додати відповідь", browse_category: "Перегляд за категоріями", faq_title: "Часті запитання",
  legal_center: "Правовий центр", legal_desc: "Все, що вам потрібно знати про роботу LUDZO, ваші права та наші правила.", terms_cond: "Умови та положення", privacy_policy: "Політика конфіденційності", resp_gaming: "Відповідальна гра", refund_policy: "Політика повернення", aml_policy: "Політика AML та боротьби з шахрайством", fair_play: "Правила чесної гри", support_disputes: "Підтримка та спори",
  under_maintenance: "На технічному обслуговуванні", maintenance_desc: "LUDZO перебуває на плановому обслуговуванні. Будь ласка, завітайте пізніше.",
};

const ES: Record<string, string> = { ...EN,
  nav_home: "Inicio", nav_tasks: "Tareas", nav_games: "Juegos", nav_refer: "Referir", nav_profile: "Perfil", nav_play: "Jugar", nav_matches: "Partidas", nav_settings: "Ajustes", nav_arena: "Arena Ludo",
  loading: "Cargando...", error: "Algo salió mal", retry: "Reintentar", cancel: "Cancelar", save: "Guardar", confirm: "Confirmar", close: "Cerrar", submit: "Enviar", back: "Atrás", next: "Siguiente", done: "Hecho", copy: "Copiar", share: "Compartir", copied: "¡Copiado!", search: "Buscar", all: "Todos", status: "Estado", date: "Fecha", amount: "Monto", view_all: "Ver todo", details: "Detalles", success: "Éxito", failed: "Fallido", coins: "Monedas", usdt: "USDT", won_coins: "Monedas ganadas", or: "o",
  splash_tagline: "Tu próximo movimiento empieza aquí.", splash_bottom: "JUEGA. GANA. REPITE.", onboarding_kicker: "EMPECEMOS", onboarding_title: "Un espacio que habla tu idioma.", onboarding_subtitle: "Elige tu idioma preferido. Puedes cambiarlo más tarde en ajustes.", onboarding_continue: "Continuar", onboarding_secure: "Inicio de sesión seguro con Telegram",
  sign_in_tg: "Iniciar sesión con Telegram", dev_mode: "Continuar (Modo Dev)", authenticating: "Autenticando...", verifying_tg: "Verificando tu identidad de Telegram", welcome_ludzo: "¡Bienvenido a LUDZO!", redirecting: "Redirigiendo...", connect_title: "Conectémonos", connect_no_tg: "No se pudo detectar Telegram. Abre esta aplicación dentro de Telegram.",
  welcome_user: "Bienvenido de nuevo, {name}", workspace_sub: "Esto es lo que sucede en tu espacio de trabajo.", eyebrow: "EL ESPACIO LUDZO", hero_heading: "Haz que tu próximo movimiento cuente.", hero_desc: "Juega una ronda. Mantén tu racha. Guarda todas tus recompensas en un solo lugar.", enter_arena: "Entrar a la arena", your_wallet: "Tu billetera", balances_glance: "Saldos de un vistazo", recent_activity: "Actividad reciente", no_activity: "Sin actividad aún", no_activity_desc: "¡Empieza a ver anuncios o jugar para ganar monedas!", top_earners: "Mejores ganancias", announcements: "Anuncios",
  playable_coins: "Monedas jugables", available_balance: "Saldo disponible", won_coins_title: "Monedas ganadas", ready_to_withdraw: "Listo para retirar", convertible_value: "${amount} convertible", ludo_prizes_note: "Premios de Ludo · {rate} Monedas ganadas = $1", coins_rate_note: "{rate} Monedas = $1", deposit: "Depositar", withdraw: "Retirar",
  deposit_title: "Comprar Monedas", select_network: "Seleccionar Red", complete_payment: "Completar Pago", current_balance: "Saldo Actual", select_amount: "Seleccionar Monto", custom_amount: "Monto personalizado ({min}–{max})", custom_hint: "Ingresa el número exacto de monedas que deseas recibir.", you_pay: "Pagas", continue_amount: "Continuar — {count} Monedas (${amount})", choose_network: "Elegir red de pago", important_notice: "Aviso Importante", deposit_notice_text: "Se debe recibir la cantidad exacta mostrada por Ludzo después de las tarifas de red.", agree_terms: "Entiendo y acepto que debe recibirse la cantidad exacta después de todas las tarifas de red y cambio.", generate_address: "Generar Dirección de Pago", creating_payment: "Creando Pago…", deposit_history: "Historial de Depósitos", no_deposits: "Sin depósitos aún", no_deposits_desc: "Realiza tu primer depósito arriba.",
  withdraw_title: "Retirar USDT", withdrawal_request: "Solicitud de Retiro", min_withdraw_note: "El retiro mínimo es de ${amount}", fee_note: "Se aplica una tarifa de retiro del {fee}%", review_note: "Los retiros se revisan manualmente en un plazo de 48 horas", wallet_address_label: "Dirección de Billetera (TRC20 / BEP20)", submit_withdrawal: "Enviar Solicitud de Retiro", submitting: "Enviando…", withdrawal_history: "Historial de Retiros", no_withdrawals: "Sin retiros aún", no_withdrawals_desc: "Solicita tu primer retiro arriba.", insufficient_balance: "Saldo insuficiente",
  rewarded_ads: "Anuncios recompensados", limit_reached: "Límite diario alcanzado · vuelve mañana", ads_left_today: "{remaining} restantes hoy", watch_ad: "Ver anuncio", earned_coins_toast: "¡+{amount} Monedas ganadas!", coins_per_ad: "+{amount} monedas / anuncio",
  daily_streak: "Racha diaria", day_claimed: "Día {n} reclamado", day_of_7: "Día {n} de 7", earned_today: "ganado hoy", coins_today: "monedas hoy", come_back_tomorrow: "Vuelve mañana para el Día {n}", bonus_ads_progress: "Anuncios de bonificación {count}/{needed}", bonus_ad_btn: "Anuncio extra", claim_btn: "Reclamar", streak_claimed_toast: "¡Día {n} de racha reclamado! +{amount} Monedas",
  tasks_title: "Tareas", available: "Disponibles", completed: "Completadas", no_available_tasks: "¡Todas las tareas completadas!", no_available_tasks_desc: "Vuelve más tarde para ver nuevas tareas.", open_channel: "Abrir Canal", start_task: "Iniciar Tarea", verify_claim: "Verificar y Reclamar", bot_check_note: "Las monedas se otorgan solo al unirte — el bot verifica la suscripción.", already_done: "Tarea ya completada",
  refer_title: "Referir y Ganar", referrals_stat: "Referidos", total_stat: "Total", pending_stat: "Pendiente", your_referral_link: "Tu Enlace de Referido", copy_link: "Copiar Enlace", how_it_works: "Cómo Funciona", refer_step_1: "Comparte tu enlace de referido único", refer_step_2: "Un nuevo usuario se une y recibe 10 monedas de bono", refer_step_3: "Hacen su primer depósito", refer_step_4: "Ganas el 10% de comisión en USDT", referral_history: "Historial de Referidos", no_referrals_yet: "Sin referidos aún", no_referrals_desc: "Comparte tu enlace para empezar a ganar comisiones.",
  leaderboard_title: "Tabla de Clasificación", leaderboard_sub: "Mejores jugadores ganando recompensas en LUDZO", weekly: "Semanal", monthly: "Mensual", all_time: "Histórico", rank: "Rango", player: "Jugador", earned: "Ganado", your_rank: "Tu Rango", no_leaderboard: "No hay datos de clasificación disponibles aún.",
  profile_title: "Perfil", wallet_summary: "Resumen de Billetera", coins_wallet: "Billetera de Monedas", cash_wallet: "Billetera de Efectivo", won_coins_ludo: "Monedas Ganadas (Premios Ludo)", menu_ludo: "Arena Ludo", menu_history: "Historial de Transacciones", menu_leaderboard: "Tabla de Clasificación", menu_refer: "Referir y Ganar", menu_faq: "Preguntas Frecuentes", menu_support: "Soporte", menu_disputes: "Soporte y Disputas", menu_settings: "Ajustes", menu_legal: "Centro Legal", sign_out: "Cerrar Sesión",
  appearance: "Apariencia", theme_dark: "Oscuro", theme_light: "Claro", theme_system: "Sistema", language_setting: "Idioma", language_sub: "Elige cómo te habla LUDZO", languages_available: "{count} disponibles", save_settings: "Guardar Ajustes", settings_saved: "¡Ajustes guardados!", failed_save: "Error al guardar ajustes",
  history_title: "Historial de Transacciones", filter_deposits: "Depósitos", filter_withdrawals: "Retiros", filter_ads: "Anuncios", filter_tasks: "Tareas", filter_referrals: "Referidos", no_transactions: "Sin transacciones", no_transactions_desc: "No se encontraron transacciones para este filtro.", load_more: "Cargar más",
  gamer_lobby: "Lobby del Jugador", exit_hub: "Salir del Hub", ludo_clash: "LUDO CLASH", ludo_desc: "Compite con jugadores en vivo, tira los dados y reclama el pozo de monedas.", play_ludo_now: "Jugar Ludo Ahora", recent_battles: "Batallas Recientes", no_battles: "Sin batallas aún", no_battles_desc: "Tus partidas terminadas y resultados aparecerán aquí.", choose_stake: "Elige tu apuesta", winner_payout: "El ganador recibe el 98% del pozo", how_to_play: "Cómo jugar", play_for_stake: "Jugar por {amount} Monedas", confirm_entry: "Entrar por {count} Monedas", confirm_sub: "Tu apuesta se mantiene en garantía hasta que termine la partida.", join_match: "Unirse a la partida", searching_opponent: "Buscando oponente", cancel_matchmaking: "Cancelar búsqueda", your_turn: "Tu turno", opponents_turn: "Turno del oponente", roll_btn: "¡Tirar!", rolling: "Tirando", rolled: "Salió", forfeit_match: "¿Rendirse?", forfeit_desc: "Perderás tu apuesta de {amount} monedas. Tu oponente se lleva el pozo.", keep_playing: "Seguir Jugando", forfeit_btn: "Rendirse", victory: "¡VICTORIA!", defeated: "DERROTADO", victory_desc: "¡Excelente juego! Recompensas acreditadas a tu saldo de Monedas Ganadas.", defeated_desc: "¡Una partida difícil! Vuelve más fuerte la próxima vez.", return_lobby: "Volver al Lobby", tap_to_move: "Toca una ficha para mover", battle_history: "Historial de Batallas", game_profile: "Perfil de Juego", clear_cache: "Limpiar Caché Local", cache_cleared: "Caché local limpiada — saldos recargados del servidor.",
  support_title: "Soporte", chat_support: "Chatear con Soporte", chat_support_desc: "Obtén ayuda instantánea vía Telegram. Tiempo de respuesta: normalmente unas horas.", open_telegram: "Abrir Telegram", submit_ticket: "Enviar un Ticket", category: "Categoría", subject: "Asunto", message: "Mensaje", send_ticket: "Enviar Ticket", ticket_submitted: "¡Ticket Enviado!", my_tickets: "Mis Tickets", no_tickets: "Sin tickets aún. Envía uno arriba y aparecerá aquí.", add_reply: "+ Agregar respuesta", browse_category: "Navegar por Categoría", faq_title: "Preguntas Frecuentes",
  legal_center: "Centro Legal", legal_desc: "Todo lo que necesitas saber sobre cómo funciona LUDZO, tus derechos y nuestras políticas.", terms_cond: "Términos y Condiciones", privacy_policy: "Política de Privacidad", resp_gaming: "Juego Responsable", refund_policy: "Política de Reembolso", aml_policy: "Política PLA y Anti-Fraude", fair_play: "Política de Juego Limpio", support_disputes: "Soporte y Disputas",
  under_maintenance: "En Mantenimiento", maintenance_desc: "LUDZO está en mantenimiento programado. Por favor, vuelve pronto.",
};

const PT: Record<string, string> = { ...EN,
  nav_home: "Início", nav_tasks: "Tarefas", nav_games: "Jogos", nav_refer: "Indicar", nav_profile: "Perfil", nav_play: "Jogar", nav_matches: "Partidas", nav_settings: "Configurações", nav_arena: "Arena Ludo",
  loading: "Carregando...", error: "Algo deu errado", retry: "Tentar novamente", cancel: "Cancelar", save: "Salvar", confirm: "Confirmar", close: "Fechar", submit: "Enviar", back: "Voltar", next: "Próximo", done: "Concluído", copy: "Copiar", share: "Compartilhar", copied: "Copiado!", search: "Buscar", all: "Todos", status: "Status", date: "Data", amount: "Valor", view_all: "Ver tudo", details: "Detalhes", success: "Sucesso", failed: "Falhou", coins: "Moedas", usdt: "USDT", won_coins: "Moedas ganhas", or: "ou",
  splash_tagline: "Sua próxima jogada começa aqui.", splash_bottom: "JOGUE. GANHE. REPITA.", onboarding_kicker: "VAMOS COMEÇAR", onboarding_title: "Um espaço que fala o seu idioma.", onboarding_subtitle: "Escolha seu idioma preferido. Você pode alterá-lo mais tarde nas configurações.", onboarding_continue: "Continuar", onboarding_secure: "Login seguro com o Telegram",
  sign_in_tg: "Entrar com Telegram", dev_mode: "Continuar (Modo Dev)", authenticating: "Autenticando...", verifying_tg: "Verificando sua identidade do Telegram", welcome_ludzo: "Bem-vindo ao LUDZO!", redirecting: "Redirecionando...", connect_title: "Vamos conectar você", connect_no_tg: "Não foi possível detectar o Telegram. Abra este aplicativo dentro do Telegram.",
  welcome_user: "Bem-vindo de volta, {name}", workspace_sub: "Aqui está o que está acontecendo no seu espaço.", eyebrow: "ESPAÇO LUDZO", hero_heading: "Faça sua próxima jogada valer a pena.", hero_desc: "Jogue uma rodada. Mantenha sua sequência. Guarde todas as recompensas num só lugar.", enter_arena: "Entrar na arena", your_wallet: "Sua carteira", balances_glance: "Saldos num relance", recent_activity: "Atividade recente", no_activity: "Sem atividade ainda", no_activity_desc: "Comece a ver anúncios ou jogar para ganhar moedas!", top_earners: "Maiores ganhadores", announcements: "Anúncios",
  playable_coins: "Moedas jogáveis", available_balance: "Saldo disponível", won_coins_title: "Moedas ganhas", ready_to_withdraw: "Pronto para retirar", convertible_value: "${amount} convertível", ludo_prizes_note: "Prêmios do Ludo · {rate} Moedas ganhas = $1", coins_rate_note: "{rate} Moedas = $1", deposit: "Depositar", withdraw: "Sacar",
  deposit_title: "Comprar Moedas", select_network: "Selecionar Rede", complete_payment: "Concluir Pagamento", current_balance: "Saldo Atual", select_amount: "Selecionar Valor", custom_amount: "Valor personalizado ({min}–{max})", custom_hint: "Digite o número exato de moedas que deseja receber.", you_pay: "Você paga", continue_amount: "Continuar — {count} Moedas (${amount})", choose_network: "Escolher rede de pagamento", important_notice: "Aviso Importante", deposit_notice_text: "O valor exato do pagamento mostrado pelo Ludzo deve ser recebido após taxas de rede.", agree_terms: "Eu entendo e concordo que o valor exato do pagamento deve ser recebido após todas as taxas.", generate_address: "Gerar Endereço de Pagamento", creating_payment: "Criando Pagamento…", deposit_history: "Histórico de Depósitos", no_deposits: "Nenhum depósito ainda", no_deposits_desc: "Faça seu primeiro depósito acima.",
  withdraw_title: "Sacar USDT", withdrawal_request: "Solicitação de Saque", min_withdraw_note: "O saque mínimo é de ${amount}", fee_note: "Aplica-se uma taxa de saque de {fee}%", review_note: "Os saques são revisados manualmente em até 48 horas", wallet_address_label: "Endereço da Carteira (TRC20 / BEP20)", submit_withdrawal: "Enviar Solicitação de Saque", submitting: "Enviando…", withdrawal_history: "Histórico de Saques", no_withdrawals: "Nenhum saque ainda", no_withdrawals_desc: "Solicite seu primeiro saque acima.", insufficient_balance: "Saldo insuficiente",
  rewarded_ads: "Anúncios recompensados", limit_reached: "Limite diário atingido · volte amanhã", ads_left_today: "{remaining} restantes hoje", watch_ad: "Assistir anúncio", earned_coins_toast: "+{amount} Moedas ganhas!", coins_per_ad: "+{amount} moedas / anúncio",
  daily_streak: "Sequência diária", day_claimed: "Dia {n} resgatado", day_of_7: "Dia {n} de 7", earned_today: "ganho hoje", coins_today: "moedas hoje", come_back_tomorrow: "Volte amanhã para o Dia {n}", bonus_ads_progress: "Anúncios bônus {count}/{needed}", bonus_ad_btn: "Anúncio bônus", claim_btn: "Resgatar", streak_claimed_toast: "Dia {n} da sequência resgatado! +{amount} Moedas",
  tasks_title: "Tarefas", available: "Disponíveis", completed: "Concluídas", no_available_tasks: "Todas as tarefas concluídas!", no_available_tasks_desc: "Volte mais tarde para novas tarefas.", open_channel: "Abrir Canal", start_task: "Iniciar Tarefa", verify_claim: "Verificar e Resgatar", bot_check_note: "As moedas são concedidas apenas ao entrar — o bot verifica a inscrição.", already_done: "Tarefa já concluída",
  refer_title: "Indicar e Ganhar", referrals_stat: "Indicações", total_stat: "Total", pending_stat: "Pendente", your_referral_link: "Seu Link de Indicação", copy_link: "Copiar Link", how_it_works: "Como Funciona", refer_step_1: "Compartilhe seu link de indicação único", refer_step_2: "Um novo usuário entra e ganha 10 moedas de bônus", refer_step_3: "Ele faz o primeiro depósito", refer_step_4: "Você ganha 10% de comissão em USDT", referral_history: "Histórico de Indicações", no_referrals_yet: "Nenhuma indicação ainda", no_referrals_desc: "Compartilhe seu link para começar a ganhar comissão.",
  leaderboard_title: "Classificação", leaderboard_sub: "Melhores jogadores ganhando recompensas no LUDZO", weekly: "Semanal", monthly: "Mensal", all_time: "Geral", rank: "Posição", player: "Jogador", earned: "Ganho", your_rank: "Sua Posição", no_leaderboard: "Nenhum dado de classificação disponível ainda.",
  profile_title: "Perfil", wallet_summary: "Resumo da Carteira", coins_wallet: "Carteira de Moedas", cash_wallet: "Carteira em Dinheiro", won_coins_ludo: "Moedas Ganhas (Prêmios Ludo)", menu_ludo: "Arena Ludo", menu_history: "Histórico de Transações", menu_leaderboard: "Classificação", menu_refer: "Indicar e Ganhar", menu_faq: "Perguntas Frequentes", menu_support: "Suporte", menu_disputes: "Suporte e Disputas", menu_settings: "Configurações", menu_legal: "Centro Legal", sign_out: "Sair",
  appearance: "Aparência", theme_dark: "Escuro", theme_light: "Claro", theme_system: "Sistema", language_setting: "Idioma", language_sub: "Escolha como o LUDZO fala com você", languages_available: "{count} disponíveis", save_settings: "Salvar Configurações", settings_saved: "Configurações salvas!", failed_save: "Falha ao salvar configurações",
  history_title: "Histórico de Transações", filter_deposits: "Depósitos", filter_withdrawals: "Saques", filter_ads: "Anúncios", filter_tasks: "Tarefas", filter_referrals: "Indicações", no_transactions: "Sem transações", no_transactions_desc: "Nenhuma transação encontrada para este filtro.", load_more: "Carregar Mais",
  gamer_lobby: "Lobby do Jogador", exit_hub: "Sair do Hub", ludo_clash: "LUDO CLASH", ludo_desc: "Enfrente jogadores ao vivo, jogue os dados e garanta o prêmio em moedas.", play_ludo_now: "Jogar Ludo Agora", recent_battles: "Batalhas Recentes", no_battles: "Nenhuma batalha ainda", no_battles_desc: "Suas partidas finalizadas e resultados de moedas aparecerão aqui.", choose_stake: "Escolha sua aposta", winner_payout: "O vencedor recebe 98% do prêmio", how_to_play: "Como jogar", play_for_stake: "Jogar por {amount} Moedas", confirm_entry: "Entrar por {count} Moedas", confirm_sub: "Sua aposta fica retida até o término da partida.", join_match: "Entrar na partida", searching_opponent: "Procurando oponente", cancel_matchmaking: "Cancelar busca", your_turn: "Sua vez", opponents_turn: "Vez do oponente", roll_btn: "Rolar!", rolling: "Rolando", rolled: "Saiu", forfeit_match: "Desistir?", forfeit_desc: "Você perderá sua aposta de {amount} moedas. Seu oponente leva o prêmio.", keep_playing: "Continuar Jogando", forfeit_btn: "Desistir", victory: "VITÓRIA!", defeated: "DERROTADO", victory_desc: "Excelente jogo! Recompensas creditadas no seu saldo de Moedas Ganhas.", defeated_desc: "Partida difícil! Volte mais forte na próxima vez.", return_lobby: "Voltar ao Lobby", tap_to_move: "Toque numa peça para mover", battle_history: "Histórico de Batalhas", game_profile: "Perfil do Jogo", clear_cache: "Limpar Cache Local", cache_cleared: "Cache local limpo — saldos recarregados do servidor.",
  support_title: "Suporte", chat_support: "Chat de Suporte", chat_support_desc: "Obtenha ajuda instantânea via Telegram. Tempo de resposta: geralmente poucas horas.", open_telegram: "Abrir Telegram", submit_ticket: "Enviar Ticket", category: "Categoria", subject: "Assunto", message: "Mensagem", send_ticket: "Enviar Ticket", ticket_submitted: "Ticket Enviado!", my_tickets: "Meus Tickets", no_tickets: "Nenhum ticket ainda. Envie um acima para ser exibido aqui.", add_reply: "+ Adicionar resposta", browse_category: "Navegar por Categoria", faq_title: "Perguntas Frequentes",
  legal_center: "Centro Legal", legal_desc: "Tudo o que você precisa saber sobre o funcionamento do LUDZO, seus direitos e nossas políticas.", terms_cond: "Termos e Condições", privacy_policy: "Política de Privacidade", resp_gaming: "Jogo Responsável", refund_policy: "Política de Reembolso", aml_policy: "Política PLD e Antifraude", fair_play: "Jogo Limpo", support_disputes: "Suporte e Disputas",
  under_maintenance: "Em Manutenção", maintenance_desc: "O LUDZO está em manutenção programada. Por favor, volte em breve.",
};

const FR: Record<string, string> = { ...EN,
  nav_home: "Accueil", nav_tasks: "Tâches", nav_games: "Jeux", nav_refer: "Parrainer", nav_profile: "Profil", nav_play: "Jouer", nav_matches: "Matchs", nav_settings: "Paramètres", nav_arena: "Arène Ludo",
  loading: "Chargement...", error: "Un problème est survenu", retry: "Réessayer", cancel: "Annuler", save: "Enregistrer", confirm: "Confirmer", close: "Fermer", submit: "Soumettre", back: "Retour", next: "Suivant", done: "Terminé", copy: "Copier", share: "Partager", copied: "Copié !", search: "Rechercher", all: "Tous", status: "Statut", date: "Date", amount: "Montant", view_all: "Voir tout", details: "Détails", success: "Succès", failed: "Échec", coins: "Pièces", usdt: "USDT", won_coins: "Pièces gagnées", or: "ou",
  splash_tagline: "Votre prochain coup commence ici.", splash_bottom: "JOUEZ. GAGNEZ. RÉPÉTEZ.", onboarding_kicker: "C'EST PARTI", onboarding_title: "Un espace qui parle votre langue.", onboarding_subtitle: "Choisissez votre langue préférée. Vous pourrez la modifier plus tard dans les paramètres.", onboarding_continue: "Continuer", onboarding_secure: "Connexion sécurisée avec Telegram",
  sign_in_tg: "Se connecter avec Telegram", dev_mode: "Continuer (Mode Dev)", authenticating: "Authentification...", verifying_tg: "Vérification de votre identité Telegram", welcome_ludzo: "Bienvenue sur LUDZO !", redirecting: "Redirection...", connect_title: "Connectons-nous", connect_no_tg: "Impossible de détecter Telegram. Veuillez ouvrir cette application dans Telegram.",
  welcome_user: "Ravi de vous revoir, {name}", workspace_sub: "Voici ce qui se passe dans votre espace.", eyebrow: "L'ESPACE LUDZO", hero_heading: "Faites en sorte que votre prochain coup compte.", hero_desc: "Jouez une partie. Maintenez votre série. Conservez toutes vos récompenses au même endroit.", enter_arena: "Entrer dans l'arène", your_wallet: "Votre portefeuille", balances_glance: "Aperçu des soldes", recent_activity: "Activité récente", no_activity: "Aucune activité pour le moment", no_activity_desc: "Regardez des pubs ou jouez pour gagner des pièces !", top_earners: "Meilleurs gagnants", announcements: "Annonces",
  playable_coins: "Pièces jouables", available_balance: "Solde disponible", won_coins_title: "Pièces gagnées", ready_to_withdraw: "Prêt à être retiré", convertible_value: "${amount} convertible", ludo_prizes_note: "Prix Ludo · {rate} Pièces gagnées = 1 $", coins_rate_note: "{rate} Pièces = 1 $", deposit: "Déposer", withdraw: "Retirer",
  deposit_title: "Acheter des pièces", select_network: "Sélectionner le réseau", complete_payment: "Finaliser le paiement", current_balance: "Solde actuel", select_amount: "Sélectionner le montant", custom_amount: "Montant personnalisé ({min}–{max})", custom_hint: "Entrez le nombre exact de pièces que vous souhaitez recevoir.", you_pay: "Vous payez", continue_amount: "Continuer — {count} Pièces (${amount})", choose_network: "Choisir le réseau de paiement", important_notice: "Avis important", deposit_notice_text: "Le montant exact indiqué par Ludzo doit être reçu après déduction des frais de réseau.", agree_terms: "Je comprends et j'accepte que le montant exact doive être reçu après tous les frais.", generate_address: "Générer l'adresse de paiement", creating_payment: "Création du paiement…", deposit_history: "Historique des dépôts", no_deposits: "Aucun dépôt pour le moment", no_deposits_desc: "Effectuez votre premier dépôt ci-dessus.",
  withdraw_title: "Retirer des USDT", withdrawal_request: "Demande de retrait", min_withdraw_note: "Le retrait minimum est de ${amount}", fee_note: "Des frais de retrait de {fee}% s'appliquent", review_note: "Les retraits sont examinés manuellement sous 48 heures", wallet_address_label: "Adresse du portefeuille (TRC20 / BEP20)", submit_withdrawal: "Soumettre la demande de retrait", submitting: "Soumission…", withdrawal_history: "Historique des retraits", no_withdrawals: "Aucun retrait pour le moment", no_withdrawals_desc: "Effectuez votre premier retrait ci-dessus.", insufficient_balance: "Solde insuffisant",
  rewarded_ads: "Publicités récompensées", limit_reached: "Limite quotidienne atteinte · revenez demain", ads_left_today: "{remaining} restantes aujourd'hui", watch_ad: "Regarder la pub", earned_coins_toast: "+{amount} Pièces gagnées !", coins_per_ad: "+{amount} pièces / pub",
  daily_streak: "Série quotidienne", day_claimed: "Jour {n} réclamé", day_of_7: "Jour {n} sur 7", earned_today: "gagné aujourd'hui", coins_today: "pièces aujourd'hui", come_back_tomorrow: "Revenez demain pour le Jour {n}", bonus_ads_progress: "Publicités bonus {count}/{needed}", bonus_ad_btn: "Pub bonus", claim_btn: "Réclamer", streak_claimed_toast: "Série du Jour {n} réclamée ! +{amount} Pièces",
  tasks_title: "Tâches", available: "Disponibles", completed: "Terminées", no_available_tasks: "Toutes les tâches sont terminées !", no_available_tasks_desc: "Revenez plus tard pour de nouvelles tâches.", open_channel: "Ouvrir le canal", start_task: "Commencer la tâche", verify_claim: "Vérifier et Réclamer", bot_check_note: "Les pièces sont attribuées après adhésion — le bot vérifie votre abonnement.", already_done: "Tâche déjà terminée",
  refer_title: "Parrainer et Gagner", referrals_stat: "Filleuls", total_stat: "Total", pending_stat: "En attente", your_referral_link: "Votre lien de parrainage", copy_link: "Copier le lien", how_it_works: "Comment ça marche", refer_step_1: "Partagez votre lien de parrainage unique", refer_step_2: "Un nouvel utilisateur s'inscrit et reçoit 10 pièces en bonus", refer_step_3: "Il effectue son premier dépôt", refer_step_4: "Vous gagnez 10% de commission en USDT", referral_history: "Historique de parrainage", no_referrals_yet: "Aucun filleul pour le moment", no_referrals_desc: "Partagez votre lien pour commencer à gagner des commissions.",
  leaderboard_title: "Classement", leaderboard_sub: "Meilleurs joueurs gagnant des récompenses sur LUDZO", weekly: "Hebdomadaire", monthly: "Mensuel", all_time: "Général", rank: "Rang", player: "Joueur", earned: "Gagné", your_rank: "Votre rang", no_leaderboard: "Aucune donnée de classement disponible pour le moment.",
  profile_title: "Profil", wallet_summary: "Résumé du portefeuille", coins_wallet: "Portefeuille de Pièces", cash_wallet: "Portefeuille Cash", won_coins_ludo: "Pièces Gagnées (Prix Ludo)", menu_ludo: "Arène Ludo", menu_history: "Historique des transactions", menu_leaderboard: "Classement", menu_refer: "Parrainer et Gagner", menu_faq: "FAQ", menu_support: "Support", menu_disputes: "Support et Litiges", menu_settings: "Paramètres", menu_legal: "Centre Légal", sign_out: "Déconnexion",
  appearance: "Apparence", theme_dark: "Sombre", theme_light: "Clair", theme_system: "Système", language_setting: "Langue", language_sub: "Choisissez comment LUDZO s'adresse à vous", languages_available: "{count} disponibles", save_settings: "Enregistrer les paramètres", settings_saved: "Paramètres enregistrés !", failed_save: "Échec de l'enregistrement des paramètres",
  history_title: "Historique des transactions", filter_deposits: "Dépôts", filter_withdrawals: "Retraits", filter_ads: "Publicités", filter_tasks: "Tâches", filter_referrals: "Parrainages", no_transactions: "Aucune transaction", no_transactions_desc: "Aucune transaction trouvée pour ce filtre.", load_more: "Charger plus",
  gamer_lobby: "Lobby des Joueurs", exit_hub: "Quitter le Hub", ludo_clash: "LUDO CLASH", ludo_desc: "Affrontez des joueurs en direct, lancez les dés et remportez le pot de pièces.", play_ludo_now: "Jouer au Ludo Maintenant", recent_battles: "Batailles Récentes", no_battles: "Aucune bataille pour le moment", no_battles_desc: "Vos parties terminées et vos résultats en pièces apparaîtront ici.", choose_stake: "Choisissez votre mise", winner_payout: "Le gagnant reçoit 98% du pot", how_to_play: "Comment jouer", play_for_stake: "Jouer pour {amount} Pièces", confirm_entry: "Entrer pour {count} Pièces", confirm_sub: "Votre mise est bloquée jusqu'à la fin de la partie.", join_match: "Rejoindre la partie", searching_opponent: "Recherche d'un adversaire", cancel_matchmaking: "Annuler la recherche", your_turn: "À votre tour", opponents_turn: "Tour de l'adversaire", roll_btn: "Lancer !", rolling: "Lancement", rolled: "Obtenu", forfeit_match: "Abandonner ?", forfeit_desc: "Vous perdrez votre mise de {amount} pièces. Votre adversaire remporte le pot.", keep_playing: "Continuer à Jouer", forfeit_btn: "Abandonner", victory: "VICTOIRE !", defeated: "DÉFAITE", victory_desc: "Superbe partie ! Récompenses créditées sur votre solde de Pièces Gagnées.", defeated_desc: "Match difficile ! Revenez plus fort la prochaine fois.", return_lobby: "Retour au Lobby", tap_to_move: "Appuyez sur un pion pour le déplacer", battle_history: "Historique des Batailles", game_profile: "Profil de Jeu", clear_cache: "Vider le Cache Local", cache_cleared: "Cache local vidé — soldes rechargés depuis le serveur.",
  support_title: "Support", chat_support: "Discuter avec le Support", chat_support_desc: "Obtenez une aide instantanée via Telegram. Temps de réponse : généralement quelques heures.", open_telegram: "Ouvrir Telegram", submit_ticket: "Créer un Ticket", category: "Catégorie", subject: "Sujet", message: "Message", send_ticket: "Envoyer le Ticket", ticket_submitted: "Ticket Envoyé !", my_tickets: "Mes Tickets", no_tickets: "Aucun ticket pour le moment. Créez-en un ci-dessus.", add_reply: "+ Ajouter une réponse", browse_category: "Parcourir par Catégorie", faq_title: "Foire Aux Questions",
  legal_center: "Centre Légal", legal_desc: "Tout ce que vous devez savoir sur le fonctionnement de LUDZO, vos droits et nos politiques.", terms_cond: "Conditions Générales", privacy_policy: "Politique de Confidentialité", resp_gaming: "Jeu Responsable", refund_policy: "Politique de Remboursement", aml_policy: "Politique LCB-FT & Anti-Fraude", fair_play: "Jeu Équitable", support_disputes: "Support et Litiges",
  under_maintenance: "En Maintenance", maintenance_desc: "LUDZO est actuellement en maintenance programmée. Veuillez revenir sous peu.",
};

const DE: Record<string, string> = { ...EN,
  nav_home: "Start", nav_tasks: "Aufgaben", nav_games: "Spiele", nav_refer: "Empfehlen", nav_profile: "Profil", nav_play: "Spielen", nav_matches: "Spiele", nav_settings: "Einstellungen", nav_arena: "Ludo-Arena",
  loading: "Wird geladen...", error: "Etwas ist schiefgelaufen", retry: "Wiederholen", cancel: "Abbrechen", save: "Speichern", confirm: "Bestätigen", close: "Schließen", submit: "Absenden", back: "Zurück", next: "Weiter", done: "Fertig", copy: "Kopieren", share: "Teilen", copied: "Kopiert!", search: "Suchen", all: "Alle", status: "Status", date: "Datum", amount: "Betrag", view_all: "Alle anzeigen", details: "Details", success: "Erfolg", failed: "Fehlgeschlagen", coins: "Münzen", usdt: "USDT", won_coins: "Gewonnene Münzen", or: "oder",
  splash_tagline: "Dein nächster Zug beginnt hier.", splash_bottom: "SPIELEN. VERDIENEN. WIEDERHOLEN.", onboarding_kicker: "LASS UNS STARTEN", onboarding_title: "Ein Bereich, der deine Sprache spricht.", onboarding_subtitle: "Wähle deine bevorzugte Sprache. Du kannst sie später in den Einstellungen ändern.", onboarding_continue: "Weiter", onboarding_secure: "Sichere Anmeldung mit Telegram",
  sign_in_tg: "Mit Telegram anmelden", dev_mode: "Fortfahren (Dev-Modus)", authenticating: "Authentifizierung...", verifying_tg: "Telegram-Identität wird überprüft", welcome_ludzo: "Willkommen bei LUDZO!", redirecting: "Weiterleitung...", connect_title: "Lass uns dich verbinden", connect_no_tg: "Telegram konnte nicht erkannt werden. Bitte öffne diese App in Telegram.",
  welcome_user: "Willkommen zurück, {name}", workspace_sub: "Das passiert gerade in deinem Bereich.", eyebrow: "DER LUDZO BEREICH", hero_heading: "Mache deinen nächsten Zug entscheidend.", hero_desc: "Spiele eine Runde. Baue deine Serie aus. Behalte alle Belohnungen an einem Ort.", enter_arena: "Arena betreten", your_wallet: "Deine Geldbörse", balances_glance: "Guthaben auf einen Blick", recent_activity: "Letzte Aktivität", no_activity: "Noch keine Aktivität", no_activity_desc: "Schaue Werbung oder spiele, um Münzen zu verdienen!", top_earners: "Top-Verdiener", announcements: "Ankündigungen",
  playable_coins: "Spielbare Münzen", available_balance: "Verfügbares Guthaben", won_coins_title: "Gewonnene Münzen", ready_to_withdraw: "Bereit zur Auszahlung", convertible_value: "${amount} umwandelbar", ludo_prizes_note: "Ludo-Preise · {rate} Gewonnene Münzen = 1 $", coins_rate_note: "{rate} Münzen = 1 $", deposit: "Einzahlen", withdraw: "Auszahlen",
  deposit_title: "Münzen kaufen", select_network: "Netzwerk wählen", complete_payment: "Zahlung abschließen", current_balance: "Aktuelles Guthaben", select_amount: "Betrag wählen", custom_amount: "Wunschbetrag ({min}–{max})", custom_hint: "Gib die genaue Anzahl an Münzen ein, die du erhalten möchtest.", you_pay: "Du zahlst", continue_amount: "Weiter — {count} Münzen (${amount})", choose_network: "Zahlungsnetzwerk wählen", important_notice: "Wichtiger Hinweis", deposit_notice_text: "Der genaue Zahlungsbetrag muss nach Abzug der Netzwerkgebühren eingehen.", agree_terms: "Ich verstehe und stimme zu, dass der genaue Betrag nach Abzug aller Gebühren eingehen muss.", generate_address: "Zahlungsadresse generieren", creating_payment: "Zahlung wird erstellt…", deposit_history: "Einzahlungshistorie", no_deposits: "Noch keine Einzahlungen", no_deposits_desc: "Tätige oben deine erste Einzahlung.",
  withdraw_title: "USDT auszahlen", withdrawal_request: "Auszahlungsantrag", min_withdraw_note: "Mindestauszahlung beträgt ${amount}", fee_note: "Es fällt eine Auszahlungsgebühr von {fee}% an", review_note: "Auszahlungen werden innerhalb von 48 Stunden manuell geprüft", wallet_address_label: "Wallet-Adresse (TRC20 / BEP20)", submit_withdrawal: "Auszahlung beantragen", submitting: "Wird gesendet…", withdrawal_history: "Auszahlungshistorie", no_withdrawals: "Noch keine Auszahlungen", no_withdrawals_desc: "Beantrage oben deine erste Auszahlung.", insufficient_balance: "Unzureichendes Guthaben",
  rewarded_ads: "Belohnte Werbung", limit_reached: "Tageslimit erreicht · komm morgen wieder", ads_left_today: "Heute noch {remaining} übrig", watch_ad: "Werbung ansehen", earned_coins_toast: "+{amount} Münzen verdient!", coins_per_ad: "+{amount} Münzen / Werbung",
  daily_streak: "Tägliche Serie", day_claimed: "Tag {n} abgeholt", day_of_7: "Tag {n} von 7", earned_today: "heute verdient", coins_today: "Münzen heute", come_back_tomorrow: "Komm morgen wieder für Tag {n}", bonus_ads_progress: "Bonuswerbung {count}/{needed}", bonus_ad_btn: "Bonuswerbung", claim_btn: "Abholen", streak_claimed_toast: "Tag {n} der Serie abgeholt! +{amount} Münzen",
  tasks_title: "Aufgaben", available: "Verfügbar", completed: "Abgeschlossen", no_available_tasks: "Alle Aufgaben erledigt!", no_available_tasks_desc: "Schau später wieder vorbei für neue Aufgaben.", open_channel: "Kanal öffnen", start_task: "Aufgabe starten", verify_claim: "Prüfen & Abholen", bot_check_note: "Münzen gibt es erst nach dem Beitritt — der Bot überprüft die Mitgliedschaft.", already_done: "Aufgabe bereits erledigt",
  refer_title: "Empfehlen & Verdienen", referrals_stat: "Empfehlungen", total_stat: "Gesamt", pending_stat: "Ausstehend", your_referral_link: "Dein Empfehlungslink", copy_link: "Link kopieren", how_it_works: "So funktioniert's", refer_step_1: "Teile deinen einzigartigen Empfehlungslink", refer_step_2: "Ein neuer Nutzer tritt bei und erhält 10 Münzen Bonus", refer_step_3: "Er tätigt seine erste Einzahlung", refer_step_4: "Du erhältst 10% Provision in USDT", referral_history: "Empfehlungshistorie", no_referrals_yet: "Noch keine Empfehlungen", no_referrals_desc: "Teile deinen Link, um Provisionen zu verdienen.",
  leaderboard_title: "Bestenliste", leaderboard_sub: "Top-Spieler, die Belohnungen auf LUDZO verdienen", weekly: "Wöchentlich", monthly: "Monatlich", all_time: "Gesamtzeit", rank: "Rang", player: "Spieler", earned: "Verdient", your_rank: "Dein Rang", no_leaderboard: "Noch keine Daten für die Bestenliste vorhanden.",
  profile_title: "Profil", wallet_summary: "Geldbörsen-Übersicht", coins_wallet: "Münz-Geldbörse", cash_wallet: "Bargeld-Geldbörse", won_coins_ludo: "Gewonnene Münzen (Ludo-Preise)", menu_ludo: "Ludo-Arena", menu_history: "Transaktionsverlauf", menu_leaderboard: "Bestenliste", menu_refer: "Empfehlen & Verdienen", menu_faq: "FAQ", menu_support: "Support", menu_disputes: "Support & Streitfälle", menu_settings: "Einstellungen", menu_legal: "Rechtszentrum", sign_out: "Abmelden",
  appearance: "Erscheinungsbild", theme_dark: "Dunkel", theme_light: "Hell", theme_system: "System", language_setting: "Sprache", language_sub: "Wähle, wie LUDZO mit dir spricht", languages_available: "{count} verfügbar", save_settings: "Einstellungen speichern", settings_saved: "Einstellungen gespeichert!", failed_save: "Fehler beim Speichern der Einstellungen",
  history_title: "Transaktionsverlauf", filter_deposits: "Einzahlungen", filter_withdrawals: "Auszahlungen", filter_ads: "Werbung", filter_tasks: "Aufgaben", filter_referrals: "Empfehlungen", no_transactions: "Keine Transaktionen", no_transactions_desc: "Keine Transaktionen für diesen Filter gefunden.", load_more: "Mehr laden",
  gamer_lobby: "Gamer-Lobby", exit_hub: "Hub verlassen", ludo_clash: "LUDO CLASH", ludo_desc: "Trete live gegen Spieler an, würfele und sichere dir den Münztopf.", play_ludo_now: "Jetzt Ludo spielen", recent_battles: "Letzte Kämpfe", no_battles: "Noch keine Kämpfe", no_battles_desc: "Deine beendeten Spiele und Münzergebnisse werden hier angezeigt.", choose_stake: "Wähle deinen Einsatz", winner_payout: "Gewinner erhält 98% des Pots", how_to_play: "Spielanleitung", play_for_stake: "Für {amount} Münzen spielen", confirm_entry: "Für {count} Münzen beitreten", confirm_sub: "Dein Einsatz wird bis zum Ende des Spiels treuhänderisch gehalten.", join_match: "Spiel beitreten", searching_opponent: "Gegnersuche…", cancel_matchmaking: "Suche abbrechen", your_turn: "Du bist dran", opponents_turn: "Gegner ist dran", roll_btn: "Würfeln!", rolling: "Würfelt", rolled: "Gewürfelt", forfeit_match: "Aufgeben?", forfeit_desc: "Du verlierst deinen Einsatz von {amount} Münzen. Dein Gegner erhält den Pot.", keep_playing: "Weiterspielen", forfeit_btn: "Aufgeben", victory: "SIEG!", defeated: "NIEDERLAGE", victory_desc: "Hervorragendes Spiel! Belohnungen deinem Guthaben gutgeschrieben.", defeated_desc: "Schweres Spiel! Komm beim nächsten Mal strak zurück.", return_lobby: "Zurück zur Lobby", tap_to_move: "Tippe auf eine Figur zum Ziehen", battle_history: "Kampfverlauf", game_profile: "Spielerprofil", clear_cache: "Lokalen Cache leeren", cache_cleared: "Lokaler Cache geleert — Guthaben vom Server neu geladen.",
  support_title: "Support", chat_support: "Support-Chat", chat_support_desc: "Erhalte sofortige Hilfe über Telegram. Antwortzeit: meist innerhalb weniger Stunden.", open_telegram: "Telegram öffnen", submit_ticket: "Ticket erstellen", category: "Kategorie", subject: "Betreff", message: "Nachricht", send_ticket: "Ticket senden", ticket_submitted: "Ticket gesendet!", my_tickets: "Meine Tickets", no_tickets: "Noch keine Tickets. Erstelle oben eines.", add_reply: "+ Antwort hinzufügen", browse_category: "Nach Kategorie durchsuchen", faq_title: "Häufig gestellte Fragen",
  legal_center: "Rechtszentrum", legal_desc: "Alles, was du über die Funktionsweise von LUDZO, deine Rechte und unsere Richtlinien wissen musst.", terms_cond: "AGB & Bedingungen", privacy_policy: "Datenschutzrichtlinie", resp_gaming: "Verantwortungsvolles Spielen", refund_policy: "Rückerstattungsrichtlinie", aml_policy: "Geldwäsche- & Anti-Betrugs-Richtlinie", fair_play: "Fairplay-Richtlinie", support_disputes: "Support & Streitfälle",
  under_maintenance: "Wartungsarbeiten", maintenance_desc: "LUDZO wird derzeit gewartet. Bitte schau in Kürze wieder vorbei.",
};

const IT: Record<string, string> = { ...EN,
  nav_home: "Home", nav_tasks: "Attività", nav_games: "Giochi", nav_refer: "Invita", nav_profile: "Profilo", nav_play: "Gioca", nav_matches: "Partite", nav_settings: "Impostazioni", nav_arena: "Arena Ludo",
  loading: "Caricamento...", error: "Qualcosa è andato storto", retry: "Riprova", cancel: "Annulla", save: "Salva", confirm: "Conferma", close: "Chiudi", submit: "Invia", back: "Indietro", next: "Avanti", done: "Fatto", copy: "Copia", share: "Condividi", copied: "Copiato!", search: "Cerca", all: "Tutti", status: "Stato", date: "Data", amount: "Importo", view_all: "Mostra tutto", details: "Dettagli", success: "Successo", failed: "Fallito", coins: "Monete", usdt: "USDT", won_coins: "Monete vinte", or: "o",
  splash_tagline: "La tua prossima mossa inizia qui.", splash_bottom: "GIOCA. GUADAGNA. RIPETI.", onboarding_kicker: "INIZIAMO", onboarding_title: "Uno spazio che parla la tua lingua.", onboarding_subtitle: "Scegli la tua lingua preferita. Potrai modificarla in seguito nelle impostazioni.", onboarding_continue: "Continua", onboarding_secure: "Accesso sicuro con Telegram",
  sign_in_tg: "Accedi con Telegram", dev_mode: "Continua (Modalità Dev)", authenticating: "Autenticazione...", verifying_tg: "Verifica della tua identità Telegram", welcome_ludzo: "Benvenuto su LUDZO!", redirecting: "Reindirizzamento...", connect_title: "Connettiamoci", connect_no_tg: "Impossibile rilevare Telegram. Apri questa app all'interno di Telegram.",
  welcome_user: "Bentornato, {name}", workspace_sub: "Ecco cosa sta succedendo nel tuo spazio di lavoro.", eyebrow: "LO SPAZIO LUDZO", hero_heading: "Fai in modo che la tua prossima mossa conti.", hero_desc: "Gioca una partita. Mantieni la tua serie. Conserva tutti i tuoi premi in un unico posto.", enter_arena: "Entra nell'arena", your_wallet: "Il tuo portafoglio", balances_glance: "Saldi a colpo d'occhio", recent_activity: "Attività recente", no_activity: "Nessuna attività", no_activity_desc: "Inizia a guardare annunci o a giocare per guadagnare monete!", top_earners: "Migliori guadagni", announcements: "Annunci",
  playable_coins: "Monete giocabili", available_balance: "Saldo disponibile", won_coins_title: "Monete vinte", ready_to_withdraw: "Pronto per il prelievo", convertible_value: "${amount} convertibili", ludo_prizes_note: "Premi Ludo · {rate} Monete vinte = $1", coins_rate_note: "{rate} Monete = $1", deposit: "Deposita", withdraw: "Preleva",
  deposit_title: "Acquista Monete", select_network: "Seleziona Rete", complete_payment: "Completa Pagamento", current_balance: "Saldo Attuale", select_amount: "Seleziona Importo", custom_amount: "Importo personalizzato ({min}–{max})", custom_hint: "Inserisci il numero esatto di monete che desideri ricevere.", you_pay: "Paghi", continue_amount: "Continua — {count} Monete (${amount})", choose_network: "Scegli rete di pagamento", important_notice: "Avviso Importante", deposit_notice_text: "L'importo esatto mostrato da Ludzo deve essere ricevuto al netto delle commissioni.", agree_terms: "Comprendo e accetto che l'importo esatto debba essere ricevuto al netto di tutte le commissioni.", generate_address: "Genera Indirizzo di Pagamento", creating_payment: "Creazione Pagamento…", deposit_history: "Cronologia Depositi", no_deposits: "Nessun deposito", no_deposits_desc: "Effettua il tuo primo deposito qui sopra.",
  withdraw_title: "Preleva USDT", withdrawal_request: "Richiesta di Prelievo", min_withdraw_note: "Il prelievo minimo è di ${amount}", fee_note: "Si applica una commissione di prelievo del {fee}%", review_note: "I prelievi vengono revisionati manualmente entro 48 ore", wallet_address_label: "Indirizzo Portafoglio (TRC20 / BEP20)", submit_withdrawal: "Invia Richiesta di Prelievo", submitting: "Invio in corso…", withdrawal_history: "Cronologia Prelievi", no_withdrawals: "Nessun prelievo", no_withdrawals_desc: "Richiedi il tuo primo prelievo qui sopra.", insufficient_balance: "Saldo insufficiente",
  rewarded_ads: "Annunci con premio", limit_reached: "Limite giornaliero raggiunto · torna domani", ads_left_today: "{remaining} rimasti oggi", watch_ad: "Guarda annuncio", earned_coins_toast: "+{amount} Monete guadagnate!", coins_per_ad: "+{amount} monete / annuncio",
  daily_streak: "Serie giornaliera", day_claimed: "Giorno {n} riscattato", day_of_7: "Giorno {n} di 7", earned_today: "guadagnato oggi", coins_today: "monete oggi", come_back_tomorrow: "Torna domani per il Giorno {n}", bonus_ads_progress: "Annunci bonus {count}/{needed}", bonus_ad_btn: "Annuncio bonus", claim_btn: "Riscatta", streak_claimed_toast: "Giorno {n} della serie riscattato! +{amount} Monete",
  tasks_title: "Attività", available: "Disponibili", completed: "Completate", no_available_tasks: "Tutte le attività completate!", no_available_tasks_desc: "Torna più tardi per nuove attività.", open_channel: "Apri Canale", start_task: "Inizia Attività", verify_claim: "Verifica e Riscatta", bot_check_note: "Le monete vengono assegnate solo dopo l'iscrizione — il bot verifica l'adesione.", already_done: "Attività già completata",
  refer_title: "Invita e Guadagna", referrals_stat: "Inviti", total_stat: "Totale", pending_stat: "In attesa", your_referral_link: "Il tuo Link di Invito", copy_link: "Copia Link", how_it_works: "Come Funziona", refer_step_1: "Condividi il tuo link di invito unico", refer_step_2: "Un nuovo utente si iscrive e riceve 10 monete bonus", refer_step_3: "Effettua il suo primo deposito", refer_step_4: "Guadagni il 10% di commissione in USDT", referral_history: "Cronologia Inviti", no_referrals_yet: "Nessun invito ancora", no_referrals_desc: "Condividi il tuo link per iniziare a guadagnare commissioni.",
  leaderboard_title: "Classifica", leaderboard_sub: "Migliori giocatori che guadagnano premi su LUDZO", weekly: "Settimanale", monthly: "Mensile", all_time: "Globale", rank: "Posizione", player: "Giocatore", earned: "Guadagnato", your_rank: "La tua Posizione", no_leaderboard: "Nessun dato in classifica ancora disponibile.",
  profile_title: "Profilo", wallet_summary: "Riepilogo Portafoglio", coins_wallet: "Portafoglio Monete", cash_wallet: "Portafoglio Contanti", won_coins_ludo: "Monete Vinte (Premi Ludo)", menu_ludo: "Arena Ludo", menu_history: "Cronologia Transazioni", menu_leaderboard: "Classifica", menu_refer: "Invita e Guadagna", menu_faq: "Domande Frequenti", menu_support: "Supporto", menu_disputes: "Supporto e Controversie", menu_settings: "Impostazioni", menu_legal: "Centro Legale", sign_out: "Disconnetti",
  appearance: "Aspetto", theme_dark: "Scuro", theme_light: "Chiaro", theme_system: "Sistema", language_setting: "Lingua", language_sub: "Scegli come LUDZO ti parla", languages_available: "{count} disponibili", save_settings: "Salva Impostazioni", settings_saved: "Impostazioni salvate!", failed_save: "Impossibile salvare le impostazioni",
  history_title: "Cronologia Transazioni", filter_deposits: "Depositi", filter_withdrawals: "Prelievi", filter_ads: "Annunci", filter_tasks: "Attività", filter_referrals: "Inviti", no_transactions: "Nessuna transazione", no_transactions_desc: "Nessuna transazione trovata per questo filtro.", load_more: "Carica Altro",
  gamer_lobby: "Lobby Giocatori", exit_hub: "Esci dall'Hub", ludo_clash: "LUDO CLASH", ludo_desc: "Sfida giocatori dal vivo, lancia i dadi e conquista il montepremi in monete.", play_ludo_now: "Gioca a Ludo Ora", recent_battles: "Battaglie Recenti", no_battles: "Nessuna battaglia", no_battles_desc: "Le tue partite concluse e i risultati appariranno qui.", choose_stake: "Scegli la tua puntata", winner_payout: "Il vincitore riceve il 98% del montepremi", how_to_play: "Come giocare", play_for_stake: "Gioca per {amount} Monete", confirm_entry: "Entra per {count} Monete", confirm_sub: "La tua puntata viene trattenuta in garanzia fino al termine.", join_match: "Entra in partita", searching_opponent: "Ricerca avversario", cancel_matchmaking: "Annulla ricerca", your_turn: "Il tuo turno", opponents_turn: "Turno dell'avversario", roll_btn: "Lancia!", rolling: "Lancio", rolled: "Uscito", forfeit_match: "Abbandonare?", forfeit_desc: "Perderai la tua puntata di {amount} monete. L'avversario vince il montepremi.", keep_playing: "Continua a Giocare", forfeit_btn: "Abbandona", victory: "VITTORIA!", defeated: "SCONFITTO", victory_desc: "Grande partita! Premi accreditati sul tuo saldo Monete Vinte.", defeated_desc: "Una partita difficile! Torna più forte la prossima volta.", return_lobby: "Torna alla Lobby", tap_to_move: "Tocca una pedina per muoverla", battle_history: "Cronologia Battaglie", game_profile: "Profilo Gioco", clear_cache: "Svuota Cache Locale", cache_cleared: "Cache locale svuotata — saldi ricaricati dal server.",
  support_title: "Supporto", chat_support: "Chat di Supporto", chat_support_desc: "Ottieni assistenza immediata via Telegram. Tempo di risposta: di solito poche ore.", open_telegram: "Apri Telegram", submit_ticket: "Invia un Ticket", category: "Categoria", subject: "Oggetto", message: "Messaggio", send_ticket: "Invia Ticket", ticket_submitted: "Ticket Inviato!", my_tickets: "I miei Ticket", no_tickets: "Nessun ticket. Inviane uno qui sopra.", add_reply: "+ Aggiungi risposta", browse_category: "Sfoglia per Categoria", faq_title: "Domande Frequenti",
  legal_center: "Centro Legale", legal_desc: "Tutto ciò che devi sapere sul funzionamento di LUDZO, i tuoi diritti e le nostre regole.", terms_cond: "Termini e Condizioni", privacy_policy: "Informativa sulla Privacy", resp_gaming: "Gioco Responsabile", refund_policy: "Politica di Rimborso", aml_policy: "Politica AML e Antifrode", fair_play: "Gioco Corretto", support_disputes: "Supporto e Controversie",
  under_maintenance: "In Manutenzione", maintenance_desc: "LUDZO è attualmente in manutenzione programmata. Riprova a breve.",
};

const TR: Record<string, string> = { ...EN,
  nav_home: "Ana Sayfa", nav_tasks: "Görevler", nav_games: "Oyunlar", nav_refer: "Davet Et", nav_profile: "Profil", nav_play: "Oyna", nav_matches: "Maçlar", nav_settings: "Ayarlar", nav_arena: "Ludo Arenası",
  loading: "Yükleniyor...", error: "Bir şeyler yanlış gitti", retry: "Tekrar Dene", cancel: "İptal", save: "Kaydet", confirm: "Onayla", close: "Kapat", submit: "Gönder", back: "Geri", next: "İleri", done: "Tamam", copy: "Kopyala", share: "Paylaş", copied: "Kopyalandı!", search: "Ara", all: "Tümü", status: "Durum", date: "Tarih", amount: "Miktar", view_all: "Tümünü Gör", details: "Detaylar", success: "Başarılı", failed: "Başarısız", coins: "Jetonlar", usdt: "USDT", won_coins: "Kazanılan Jetonlar", or: "veya",
  splash_tagline: "Bir sonraki hamleniz burada başlıyor.", splash_bottom: "OYNA. KAZAN. TEKRAR ET.", onboarding_kicker: "BAŞLAYALIM", onboarding_title: "Sizin dilinizi konuşan bir alan.", onboarding_subtitle: "Tercih ettiğiniz dili seçin. Daha sonra ayarlardan değiştirebilirsiniz.", onboarding_continue: "Devam Et", onboarding_secure: "Telegram ile güvenli giriş",
  sign_in_tg: "Telegram ile Giriş Yap", dev_mode: "Devam Et (Geliştirici Modu)", authenticating: "Kimlik doğrulanıyor...", verifying_tg: "Telegram kimliğiniz doğrulanıyor", welcome_ludzo: "LUDZO'ya Hoş Geldiniz!", redirecting: "Yönlendiriliyor...", connect_title: "Bağlantınızı kuralım", connect_no_tg: "Telegram tespit edilemedi. Lütfen bu uygulamayı Telegram içinde açın.",
  welcome_user: "Tekrar hoş geldin, {name}", workspace_sub: "Alanınızda neler olup bittiğine göz atın.", eyebrow: "LUDZO ALANI", hero_heading: "Bir sonraki hamlenizi değerli kılın.", hero_desc: "Bir tur oynayın. Seri yapın. Tüm ödüllerinizi tek bir yerde toplayın.", enter_arena: "Arenaya Gir", your_wallet: "Cüzdanınız", balances_glance: "Bakiyelere hızlı bakış", recent_activity: "Son Etkinlikler", no_activity: "Henüz etkinlik yok", no_activity_desc: "Jeton kazanmak için reklam izlemeye veya oyun oynamaya başlayın!", top_earners: "En Çok Kazananlar", announcements: "Duyurular",
  playable_coins: "Oynanabilir jetonlar", available_balance: "Kullanılabilir bakiye", won_coins_title: "Kazanılan jetonlar", ready_to_withdraw: "Çekilmeye hazır", convertible_value: "${amount} dönüştürülebilir", ludo_prizes_note: "Ludo ödülleri · {rate} Kazanılan Jeton = $1", coins_rate_note: "{rate} Jeton = $1", deposit: "Yatır", withdraw: "Çek",
  deposit_title: "Jeton Satın Al", select_network: "Ağ Seçin", complete_payment: "Ödemeyi Tamamla", current_balance: "Mevcut Bakiye", select_amount: "Miktar Seçin", custom_amount: "Özel miktar ({min}–{max})", custom_hint: "Almak istediğiniz tam jeton miktarını girin.", you_pay: "Ödeyeceğiniz", continue_amount: "Devam Et — {count} Jeton (${amount})", choose_network: "Ödeme ağını seçin", important_notice: "Önemli Uyarı", deposit_notice_text: "Ludzo tarafından gösterilen tam ödeme miktarı ağ ücretleri düşüldükten sonra ulaşmalıdır.", agree_terms: "Tüm ağ ve borsa ücretlerinden sonra tam miktarın ulaşması gerektiğini anlıyor ve kabul ediyorum.", generate_address: "Ödeme Adresi Oluştur", creating_payment: "Ödeme Oluşturuluyor…", deposit_history: "Yatırma Geçmişi", no_deposits: "Henüz yatırım yok", no_deposits_desc: "Yukarıdan ilk yatırımınızı yapın.",
  withdraw_title: "USDT Çek", withdrawal_request: "Çekim Talebi", min_withdraw_note: "Minimum çekim miktarı ${amount}", fee_note: "%{fee} çekim ücreti uygulanır", review_note: "Çekimler 48 saat içinde manuel olarak incelenir", wallet_address_label: "Cüzdan Adresi (TRC20 / BEP20)", submit_withdrawal: "Çekim Talebini Gönder", submitting: "Gönderiliyor…", withdrawal_history: "Çekim Geçmişi", no_withdrawals: "Henüz çekim yok", no_withdrawals_desc: "Yukarıdan ilk çekim talebinizi oluşturun.", insufficient_balance: "Yetersiz bakiye",
  rewarded_ads: "Ödüllü reklamlar", limit_reached: "Günlük limite ulaşıldı · yarın tekrar gelin", ads_left_today: "Bugün kalan: {remaining}", watch_ad: "Reklam izle", earned_coins_toast: "+{amount} Jeton kazanıldı!", coins_per_ad: "+{amount} jeton / reklam",
  daily_streak: "Günlük seri", day_claimed: "Gün {n} alındı", day_of_7: "Gün {n} / 7", earned_today: "bugün kazanılan", coins_today: "bugünkü jetonlar", come_back_tomorrow: "Gün {n} için yarın tekrar gelin", bonus_ads_progress: "Bonus reklamlar {count}/{needed}", bonus_ad_btn: "Bonus reklam", claim_btn: "Al", streak_claimed_toast: "Gün {n} serisi alındı! +{amount} Jeton",
  tasks_title: "Görevler", available: "Kullanılabilir", completed: "Tamamlanan", no_available_tasks: "Tüm görevler tamamlandı!", no_available_tasks_desc: "Yeni görevler için daha sonra tekrar kontrol edin.", open_channel: "Kanalı Aç", start_task: "Görevi Başlat", verify_claim: "Doğrula ve Al", bot_check_note: "Jetonlar yalnızca katıldığınızda verilir — bot üyeliği doğrular.", already_done: "Görev zaten tamamlandı",
  refer_title: "Davet Et & Kazan", referrals_stat: "Davetliler", total_stat: "Toplam", pending_stat: "Bekleyen", your_referral_link: "Davet Bağlantınız", copy_link: "Bağlantıyı Kopyala", how_it_works: "Nasıl Çalışır", refer_step_1: "Benzersiz davet bağlantınızı paylaşın", refer_step_2: "Yeni kullanıcı katılır ve 10 jeton bonus alır", refer_step_3: "İlk yatırımını yapar", refer_step_4: "%10 USDT komisyon kazanırsınız", referral_history: "Davet Geçmişi", no_referrals_yet: "Henüz davet yok", no_referrals_desc: "Komisyon kazanmaya başlamak için bağlantınızı paylaşın.",
  leaderboard_title: "Sıralama", leaderboard_sub: "LUDZO'da ödül kazanan en iyi oyuncular", weekly: "Haftalık", monthly: "Aylık", all_time: "Tüm Zamanlar", rank: "Sıra", player: "Oyuncu", earned: "Kazanılan", your_rank: "Sıralamanız", no_leaderboard: "Henüz sıralama verisi bulunmuyor.",
  profile_title: "Profil", wallet_summary: "Cüzdan Özeti", coins_wallet: "Jeton Cüzdanı", cash_wallet: "Nakit Cüzdanı", won_coins_ludo: "Kazanılan Jetonlar (Ludo Ödülleri)", menu_ludo: "Ludo Arenası", menu_history: "İşlem Geçmişi", menu_leaderboard: "Sıralama", menu_refer: "Davet Et & Kazan", menu_faq: "SSS", menu_support: "Destek", menu_disputes: "Destek & Anlaşmazlıklar", menu_settings: "Ayarlar", menu_legal: "Yasal Merkez", sign_out: "Çıkış Yap",
  appearance: "Görünüm", theme_dark: "Koyu", theme_light: "Açık", theme_system: "Sistem", language_setting: "Dil", language_sub: "LUDZO'nun sizinle nasıl konuşacağını seçin", languages_available: "{count} mevcut", save_settings: "Ayarları Kaydet", settings_saved: "Ayarlar kaydedildi!", failed_save: "Ayarlar kaydedilemedi",
  history_title: "İşlem Geçmişi", filter_deposits: "Yatırımlar", filter_withdrawals: "Çekimler", filter_ads: "Reklamlar", filter_tasks: "Görevler", filter_referrals: "Davetler", no_transactions: "İşlem yok", no_transactions_desc: "Bu filtre için işlem bulunamadı.", load_more: "Daha Fazla Yükle",
  gamer_lobby: "Oyuncu Lobisi", exit_hub: "Lobiden Çık", ludo_clash: "LUDO CLASH", ludo_desc: "Canlı oyuncularla yarışın, zarları atın ve jeton havuzunu hemen kazanın.", play_ludo_now: "Şimdi Ludo Oyna", recent_battles: "Son Maçlar", no_battles: "Henüz maç yok", no_battles_desc: "Tamamlanan maçlarınız ve sonuçlarınız burada görünecektir.", choose_stake: "Bahsinizi seçin", winner_payout: "Kazanan havuzun %98'ini alır", how_to_play: "Nasıl oynanır", play_for_stake: "{amount} Jeton için oyna", confirm_entry: "{count} Jeton ile katıl", confirm_sub: "Bahsiniz maç sonuçlanana kadar güvencede tutulur.", join_match: "Maça Katıl", searching_opponent: "Rakip aranıyor", cancel_matchmaking: "Aramayı İptal Et", your_turn: "Sizin sıranız", opponents_turn: "Rakibin sırası", roll_btn: "Zar At!", rolling: "Atılıyor", rolled: "Gelen", forfeit_match: "Pes et?", forfeit_desc: "{amount} jetonluk bahsinizi kaybedersiniz. Rakip havuzu alır.", keep_playing: "Oynamaya Devam Et", forfeit_btn: "Pes Et", victory: "ZAFER!", defeated: "YENİLGİ", victory_desc: "Harika oyun! Ödüller Kazanılan Jeton bakiyenize eklendi.", defeated_desc: "Zorlu bir maçtı! Bir dahaki sefere daha güçlü dönün.", return_lobby: "Lobiye Dön", tap_to_move: "Oynatmak için taşa dokunun", battle_history: "Maç Geçmişi", game_profile: "Oyuncu Profili", clear_cache: "Yerel Önbelleği Temizle", cache_cleared: "Yerel önbellek temizlendi — bakiyeler sunucudan yenilendi.",
  support_title: "Destek", chat_support: "Destek ile Sohbet Et", chat_support_desc: "Telegram üzerinden anında yardım alın. Yanıt süresi: genellikle birkaç saat.", open_telegram: "Telegram'ı Aç", submit_ticket: "Destek Talebi Oluştur", category: "Kategori", subject: "Konu", message: "Mesaj", send_ticket: "Talebi Gönder", ticket_submitted: "Talep Gönderildi!", my_tickets: "Taleplerim", no_tickets: "Henüz talep yok. Yukarıdan bir tane oluşturun.", add_reply: "+ Yanıt Ekle", browse_category: "Kategoriye Göre Göz At", faq_title: "Sıkça Sorulan Sorular",
  legal_center: "Yasal Merkez", legal_desc: "LUDZO'nun nasıl çalıştığı, haklarınız ve politikalarımız hakkında bilmeniz gereken her şey.", terms_cond: "Şartlar ve Koşullar", privacy_policy: "Gizlilik Politikası", resp_gaming: "Sorumlu Oyun", refund_policy: "İade Politikası", aml_policy: "AML & Anti-Dolandırıcılık Politikası", fair_play: "Adil Oyun Politikası", support_disputes: "Destek & Anlaşmazlıklar",
  under_maintenance: "Bakımda", maintenance_desc: "LUDZO şu anda planlı bakımdadır. Lütfen kısa süre sonra tekrar kontrol edin.",
};

const HI: Record<string, string> = { ...EN,
  nav_home: "होम", nav_tasks: "कार्य", nav_games: "खेल", nav_refer: "रेफर", nav_profile: "प्रोफ़ाइल", nav_play: "खेलें", nav_matches: "मैच", nav_settings: "सेटिंग्स", nav_arena: "लूडो एरिना",
  loading: "लोड हो रहा है...", error: "कुछ गलत हो गया", retry: "पुनः प्रयास करें", cancel: "रद्द करें", save: "सहेजें", confirm: "पुष्टि करें", close: "बंद करें", submit: "सबमिट करें", back: "पीछे", next: "आगे", done: "हो गया", copy: "कॉपी करें", share: "शेयर करें", copied: "कॉपी हो गया!", search: "खोजें", all: "सभी", status: "स्थिति", date: "तिथि", amount: "राशि", view_all: "सभी देखें", details: "विवरण", success: "सफल", failed: "विफल", coins: "कॉइन्स", usdt: "USDT", won_coins: "जीते गए कॉइन्स", or: "या",
  splash_tagline: "आपकी अगली चाल यहाँ से शुरू होती है।", splash_bottom: "खेलें। कमाएं। दोहराएं।", onboarding_kicker: "आइए शुरू करें", onboarding_title: "एक ऐसी जगह जो आपकी भाषा बोलती है।", onboarding_subtitle: "अपनी पसंदीदा भाषा चुनें। आप इसे बाद में सेटिंग्स में बदल सकते हैं।", onboarding_continue: "जारी रखें", onboarding_secure: "Telegram के साथ सुरक्षित साइन-इन",
  sign_in_tg: "Telegram के साथ साइन इन करें", dev_mode: "जारी रखें (डेव मोड)", authenticating: "प्रमाणीकरण हो रहा है...", verifying_tg: "आपकी Telegram पहचान की पुष्टि की जा रही है", welcome_ludzo: "LUDZO में आपका स्वागत है!", redirecting: "पुनर्निर्देशित किया जा रहा है...", connect_title: "आइए आपको जोड़ते हैं", connect_no_tg: "Telegram की पहचान नहीं हो सकी। कृपया इस ऐप को Telegram के अंदर खोलें।",
  welcome_user: "वापसी पर स्वागत है, {name}", workspace_sub: "यहाँ आपके वर्कस्पेस में क्या हो रहा है देखें।", eyebrow: "LUDZO वर्कस्पेस", hero_heading: "अपनी अगली चाल को खास बनाएं।", hero_desc: "एक दौर खेलें। अपनी स्ट्राइक बनाए रखें। अपने सभी पुरस्कारों को एक जगह रखें।", enter_arena: "एरिना में प्रवेश करें", your_wallet: "आपका वॉलेट", balances_glance: "एक नज़र में बैलेंस", recent_activity: "हाल की गतिविधि", no_activity: "अभी कोई गतिविधि नहीं", no_activity_desc: "कॉइन्स कमाने के लिए विज्ञापन देखना या खेल खेलना शुरू करें!", top_earners: "शीर्ष कमाने वाले", announcements: "घोषणाएं",
  playable_coins: "खेलने योग्य कॉइन्स", available_balance: "उपलब्ध बैलेंस", won_coins_title: "जीते गए कॉइन्स", ready_to_withdraw: "निकालने के लिए तैयार", convertible_value: "${amount} परिवर्तनशील", ludo_prizes_note: "लूडो पुरस्कार · {rate} जीते गए कॉइन्स = $1", coins_rate_note: "{rate} कॉइन्स = $1", deposit: "जमा करें", withdraw: "निकालें",
  deposit_title: "कॉइन्स खरीदें", select_network: "नेटवर्क चुनें", complete_payment: "भुगतान पूरा करें", current_balance: "वर्तमान बैलेंस", select_amount: "राशि चुनें", custom_amount: "कस्टम राशि ({min}–{max})", custom_hint: "कॉइन्स की सटीक संख्या दर्ज करें जो आप प्राप्त करना चाहते हैं।", you_pay: "आप भुगतान करते हैं", continue_amount: "जारी रखें — {count} कॉइन्स (${amount})", choose_network: "भुगतान नेटवर्क चुनें", important_notice: "महत्वपूर्ण सूचना", deposit_notice_text: "नेटवर्क शुल्क के बाद Ludzo द्वारा दिखाई गई सटीक राशि प्राप्त होनी चाहिए।", agree_terms: "मैं समझता/समझती हूँ और सहमत हूँ कि शुल्क के बाद सटीक राशि प्राप्त होनी चाहिए।", generate_address: "भुगतान पता उत्पन्न करें", creating_payment: "भुगतान बनाया जा रहा है…", deposit_history: "जमा इतिहास", no_deposits: "अभी कोई जमा नहीं", no_deposits_desc: "ऊपर अपना पहला जमा करें।",
  withdraw_title: "USDT निकालें", withdrawal_request: "निकासी अनुरोध", min_withdraw_note: "न्यूनतम निकासी ${amount} है", fee_note: "{fee}% निकासी शुल्क लागू होता है", review_note: "निकासी की 48 घंटे के भीतर समीक्षा की जाती है", wallet_address_label: "वॉलेट पता (TRC20 / BEP20)", submit_withdrawal: "निकासी अनुरोध सबमिट करें", submitting: "सबमिट हो रहा है…", withdrawal_history: "निकासी इतिहास", no_withdrawals: "अभी कोई निकासी नहीं", no_withdrawals_desc: "ऊपर अपना पहला निकासी अनुरोध सबमिट करें।", insufficient_balance: "अपर्याप्त बैलेंस",
  rewarded_ads: "पुरस्कृत विज्ञापन", limit_reached: "दैनिक सीमा समाप्त · कल वापस आएं", ads_left_today: "आज {remaining} शेष हैं", watch_ad: "विज्ञापन देखें", earned_coins_toast: "+{amount} कॉइन्स कमाए गए!", coins_per_ad: "+{amount} कॉइन्स / विज्ञापन",
  daily_streak: "दैनिक स्ट्राइक", day_claimed: "दिन {n} का दावा किया गया", day_of_7: "7 में से दिन {n}", earned_today: "आज कमाए गए", coins_today: "आज के कॉइन्स", come_back_tomorrow: "दिन {n} के लिए कल वापस आएं", bonus_ads_progress: "बोनस विज्ञापन {count}/{needed}", bonus_ad_btn: "बोनस विज्ञापन", claim_btn: "दावा करें", streak_claimed_toast: "स्ट्राइक दिन {n} का दावा किया गया! +{amount} कॉइन्स",
  tasks_title: "कार्य", available: "उपलब्ध", completed: "पूरा किया गया", no_available_tasks: "सभी कार्य पूरे हो गए!", no_available_tasks_desc: "नए कार्यों के लिए बाद में जाँच करें।", open_channel: "चैनल खोलें", start_task: "कार्य शुरू करें", verify_claim: "सत्यापित करें और दावा करें", bot_check_note: "कॉइन्स केवल जुड़ने पर दिए जाते हैं — बॉट सदस्यता की जाँच करता है।", already_done: "कार्य पहले ही पूरा हो चुका है",
  refer_title: "रेफर करें और कमाएं", referrals_stat: "रेफरल्स", total_stat: "कुल", pending_stat: "लंबित", your_referral_link: "आपका रेफरल लिंक", copy_link: "लिंक कॉपी करें", how_it_works: "यह कैसे काम करता है", refer_step_1: "अपना अनूठा रेफरल लिंक साझा करें", refer_step_2: "नया उपयोगकर्ता जुड़ता है और 10 कॉइन्स बोनस पाता है", refer_step_3: "वे अपना पहला जमा करते हैं", refer_step_4: "आप USDT में 10% कमीशन कमाते हैं", referral_history: "रेफरल इतिहास", no_referrals_yet: "अभी कोई रेफरल नहीं", no_referrals_desc: "कमिशन कमाना शुरू करने के लिए अपना लिंक साझा करें।",
  leaderboard_title: "लीडरबोर्ड", leaderboard_sub: "LUDZO पर पुरस्कार कमाने वाले शीर्ष खिलाड़ी", weekly: "साप्ताहिक", monthly: "मासिक", all_time: "सर्वकालिक", rank: "रैंक", player: "खिलाड़ी", earned: "कमाए गए", your_rank: "आपकी रैंक", no_leaderboard: "अभी कोई लीडरबोर्ड डेटा उपलब्ध नहीं है।",
  profile_title: "प्रोफ़ाइल", wallet_summary: "वॉलेट सारांश", coins_wallet: "कॉइन्स वॉलेट", cash_wallet: "कैश वॉलेट", won_coins_ludo: "जीते गए कॉइन्स (लूडो पुरस्कार)", menu_ludo: "लूडो एरिना", menu_history: "लेनदेन इतिहास", menu_leaderboard: "लीडरबोर्ड", menu_refer: "रेफर करें और कमाएं", menu_faq: "सामान्य प्रश्न (FAQ)", menu_support: "सहायता", menu_disputes: "सहायता और विवाद", menu_settings: "सेटिंग्स", menu_legal: "लीगल सेंटर", sign_out: "साइन आउट करें",
  appearance: "उपस्थिति", theme_dark: "डार्क", theme_light: "लाइट", theme_system: "सिस्टम", language_setting: "भाषा", language_sub: "चुनें कि LUDZO आपसे कैसे बात करता है", languages_available: "{count} उपलब्ध हैं", save_settings: "सेटिंग्स सहेजें", settings_saved: "सेटिंग्स सहेजी गईं!", failed_save: "सेटिंग्स सहेजने में विफल",
  history_title: "लेनदेन इतिहास", filter_deposits: "जमा", filter_withdrawals: "निकासी", filter_ads: "विज्ञापन", filter_tasks: "कार्य", filter_referrals: "रेफरल्स", no_transactions: "कोई लेनदेन नहीं", no_transactions_desc: "इस फ़िल्टर के लिए कोई लेनदेन नहीं मिला।", load_more: "और लोड करें",
  gamer_lobby: "गेमर लॉबी", exit_hub: "हब से बाहर निकलें", ludo_clash: "LUDO CLASH", ludo_desc: "लाइव खिलाड़ियों से मुकाबला करें, पासा फेंकें और तुरंत कॉइन पूल जीतें।", play_ludo_now: "अब लूडो खेलें", recent_battles: "हाल के मैच", no_battles: "अभी कोई मैच नहीं हुआ", no_battles_desc: "आपके समाप्त मैच और नतीजे यहाँ दिखाई देंगे।", choose_stake: "अपनी दांव चुनें", winner_payout: "विजेता को पूल का 98% मिलता है", how_to_play: "कैसे खेलें", play_for_stake: "{amount} कॉइन्स के लिए खेलें", confirm_entry: "{count} कॉइन्स के साथ प्रवेश करें", confirm_sub: "मैच समाप्त होने तक आपकी दांव सुरक्षित रखी जाती है।", join_match: "मैच में शामिल हों", searching_opponent: "प्रतिद्वंद्वी की तलाश की जा रही है", cancel_matchmaking: "मैचमेकिंग रद्द करें", your_turn: "आपकी बारी", opponents_turn: "प्रतिद्वंद्वी की बारी", roll_btn: "पासा फेंकें!", rolling: "फेंक रहे हैं", rolled: "आया", forfeit_match: "हार मानें?", forfeit_desc: "आप {amount} कॉइन्स की दांव हार जाएंगे। प्रतिद्वंद्वी पूल जीत जाएगा।", keep_playing: "खेलना जारी रखें", forfeit_btn: "हार मानें", victory: "जीत!", defeated: "हार", victory_desc: "शानदार खेल! आपके जीते गए कॉइन्स में पुरस्कार जमा कर दिया गया।", defeated_desc: "कड़ा मैच! अगली बार और मजबूत होकर आएं।", return_lobby: "लॉबी में वापस जाएं", tap_to_move: "चाल चलने के लिए गोट पर टैप करें", battle_history: "मैच इतिहास", game_profile: "गेम प्रोफ़ाइल", clear_cache: "लोकल कैश साफ़ करें", cache_cleared: "लोकल कैश साफ़ किया गया — सर्वर से बैलेंस पुनः लोड हुआ।",
  support_title: "सहायता", chat_support: "सहायता से चैट करें", chat_support_desc: "Telegram के माध्यम से तुरंत मदद पाएं। उत्तर समय: आमतौर पर कुछ घंटे।", open_telegram: "Telegram खोलें", submit_ticket: "टिकट सबमिट करें", category: "श्रेणी", subject: "विषय", message: "संदेश", send_ticket: "टिकट भेजें", ticket_submitted: "टिकट सबमिट हो गया!", my_tickets: "मेरे टिकट", no_tickets: "अभी कोई टिकट नहीं। ऊपर एक सबमिट करें।", add_reply: "+ जवाब जोड़ें", browse_category: "श्रेणी के अनुसार ब्राउज़ करें", faq_title: "अक्सर पूछे जाने वाले प्रश्न",
  legal_center: "लीगल सेंटर", legal_desc: "LUDZO कैसे काम करता है, आपके अधिकार और हमारी नीतियों के बारे में जानने योग्य सब कुछ।", terms_cond: "नियम और शर्तें", privacy_policy: "गोपनीयता नीति", resp_gaming: "जिम्मेदार गेमिंग", refund_policy: "रिफंड नीति", aml_policy: "AML और धोखाधड़ी-विरोधी नीति", fair_play: "फेयर प्ले नीति", support_disputes: "सहायता और विवाद",
  under_maintenance: "रखरखाव के तहत", maintenance_desc: "LUDZO वर्तमान में निर्धारित रखरखाव के तहत है। कृपया जल्द ही पुनः जांचें।",
};

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: EN,
  ru: RU,
  uk: UK,
  es: ES,
  pt: PT,
  fr: FR,
  de: DE,
  it: IT,
  tr: TR,
  hi: HI,
};

export function getTranslation(lang: string, key: string, vars?: Record<string, string | number>): string {
  const code = normalizeLanguage(lang);
  let text = translations[code]?.[key] ?? translations.en?.[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replaceAll(`{${k}}`, String(v));
    }
  }
  return text;
}

export function formatNumber(value: number, lang: string = "en", options?: Intl.NumberFormatOptions): string {
  try {
    return new Intl.NumberFormat(lang, options).format(value);
  } catch {
    return value.toLocaleString();
  }
}

export function formatCurrency(amount: number, currency: string = "USD", lang: string = "en"): string {
  try {
    return new Intl.NumberFormat(lang, { style: "currency", currency }).format(amount);
  } catch {
    return `$${amount.toFixed(2)}`;
  }
}

export function formatDate(date: Date | string | number, lang: string = "en", options?: Intl.DateTimeFormatOptions): string {
  try {
    const d = typeof date === "object" ? date : new Date(date);
    return new Intl.DateTimeFormat(lang, options ?? { dateStyle: "medium" }).format(d);
  } catch {
    return String(date);
  }
}
